import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, it } from "node:test";
import { checkEffects, emitGIR, executeFlow, parseProgram } from "../../galerina-core-compiler/dist/index.js";
const ROOT=join(import.meta.dirname,"..","..",".."),PACKAGE_ROOT=join(ROOT,"packages-galerina","galerina-test"),OVERLAY_ROOT=join(PACKAGE_ROOT,"src","self-hosted","conversion-overlays"),PACKAGE=join(PACKAGE_ROOT,"package.json"),I="galerina-core-compiler/src/interpreter.ts",D="galerina-core-compiler/src/invariant-discharge.ts",L="galerina-core-compiler/src/leak-proof.ts";
const bool=value=>({__tag:"bool",value}),string=value=>({__tag:"string",value}),args=names=>new Map(names.map(name=>[name,bool(true)])),RESERVED=new Set(["version","pure","secure","flow","FLOW","contract","intent","record","return","if","match","check","deny","ambig","mut","let","Bool","Int","String","Verdict","Result","Option","Array","true","false","Ok","Err","Some","None","Allow","Deny","Unknown"]);
const RAW=Object.freeze([
  ["interpreter-resolve-char-escape",I,"function resolveCharEscape("],["interpreter-title-case",I,"function titleCase("],["interpreter-void-identifier",I,"function voidIdentifier("],["interpreter-find-string-literals",I,"function findStringLiterals("],["interpreter-find-string-literals-walk",I,"function walk(current: AstNode): void"],["interpreter-make-response-value",I,"function makeResponseValue("],["interpreter-make-api-error-value",I,"function makeApiErrorValue("],["interpreter-resolve-capability-effect",I,"function resolveCapabilityEffect("],["interpreter-extract-output-postconditions",I,"function extractOutputPostconditions("],["interpreter-expr-references-result",I,"function exprReferencesResult("],
  ["interpreter-extract-input-preconditions",I,"function extractInputPreconditions("],["interpreter-extract-param-admissions",I,"function extractParamAdmissions("],["interpreter-ast-contains-kind",I,"function astContainsKind("],["interpreter-flow-requires-governed-path",I,"function flowRequiresGovernedPath("],["interpreter-flow-requires-governed-path-walk",I,"function walk(node: AstNode): void"],["interpreter-describe-ensure-expr",I,"function describeEnsureExpr("],["interpreter-extract-request-time-ms",I,"export function extractRequestTimeMs("],["interpreter-extract-network-requests-limit",I,"export function extractNetworkRequestsLimit("],["interpreter-is-pure-effect-free",I,"function isPureEffectFree("],["interpreter-execute-flow-sync",I,"export function executeFlowSync("],
  ["interpreter-make-galerina-value",I,"function makeGalerinaValue("],["interpreter-run-from-graph",I,"function runFromGraph("],["interpreter-execute-flow",I,"export async function executeFlow("],["interpreter-assign-slots",I,"function assignSlots("],["interpreter-slotted-scope-class",I,"class SlottedScope {"],["interpreter-slotted-scope-constructor",I,"constructor(size: number)"],["interpreter-slotted-scope-get",I,"get(slot: number)"],["interpreter-slotted-scope-set",I,"set(slot: number, value: GalerinaValue)"],["interpreter-slotted-scope-size",I,"size(): number"],["interpreter-try-while-fast-path",I,"function tryWhileFastPath("],
  ["invariant-discharge-flatten-governance-conjunction",D,"export function flattenGovernanceConjunction("],["invariant-discharge-fold-static-verdict",D,"export function foldStaticVerdict("],["invariant-discharge-ensure-operands",D,"export function dischargeEnsureOperands("],
  ["leak-proof-ns-of",L,"const nsOf = (effect: string)"],["leak-proof-category-for",L,"function categoryFor("],["leak-proof-extract-capability",L,"function extractCapability("],["leak-proof-anchor",L,"function anchor("],["leak-proof-build-leak-proof",L,"export function buildLeakProof("],["leak-proof-canonical-leak-proof",L,"export function canonicalLeakProof("],["leak-proof-canonical-leak-proof-fld",L,"const fld = (l: LeakFinding)"],
]);
const camel=stem=>stem.split("-").map((p,i)=>i===0?p:p[0].toUpperCase()+p.slice(1)).join("");
const CANDIDATES=Object.freeze(RAW.map(([stem,source,symbol])=>Object.freeze({file:`${stem}-status.fungi`,flow:`${camel(stem)}StatusCore`,source,symbol,input:args(["inputCaptured","stateChecked","decisionBuilt","evidenceBound","outcomeSealed","releaseChecked"]),expected:string(`${stem.replaceAll("-","_")}_built`)})));
function shadowFingerprint(source){const identifiers=new Map();return createHash("sha256").update(source.replace(/^\uFEFF/u," ").replace(/\/\*[\s\S]*?\*\//gu," ").replace(/^\s*\/\/.*$/gmu," ").replace(/\b((?:pure|secure)\s+)?flow\s+[A-Za-z_][A-Za-z0-9_]*/gu,m=>m.replace(/([A-Za-z_][A-Za-z0-9_]*)$/u,"FLOW")).replace(/"(?:\\.|[^"\\])*"/gu,'"STRING"').replace(/\b-?(?:0x[0-9a-fA-F_]+|\d[\d_]*)\b/gu,"NUMBER").replace(/\s+/gu," ").trim().replace(/\b[A-Za-z_][A-Za-z0-9_]*\b/gu,id=>{if(RESERVED.has(id))return id;let r=identifiers.get(id);if(r===undefined){r="ID"+identifiers.size;identifiers.set(id,r);}return r;}),"utf8").digest("hex");}
describe("40-file source-bound Fungi decision-core overlay wave 39",()=>{
  it("binds 40 distinct, previously uncredited live source behaviours and package assets",()=>{assert.equal(CANDIDATES.length,40);const loaded=JSON.parse(readFileSync(PACKAGE,"utf8")).packageGraph?.loadedAssets??[],scopes=new Set();for(const c of CANDIDATES){assert.ok(loaded.includes(`src/self-hosted/conversion-overlays/${c.file}`),`${c.file} must be a loaded asset`);const source=readFileSync(join(ROOT,"packages-galerina",c.source),"utf8");assert.ok(source.includes(c.symbol),`${c.source} must contain ${c.symbol}`);const scope=`${c.source}#${c.flow}`;assert.equal(scopes.has(scope),false);scopes.add(scope);}});
  it("has no exact duplicate or normalized whole-corpus template shadow",()=>{const seen=new Map(),files=new Set(CANDIDATES.map(c=>c.file));for(const file of readdirSync(OVERLAY_ROOT).filter(f=>f.endsWith(".fungi")&&!files.has(f))){const source=readFileSync(join(OVERLAY_ROOT,file),"utf8");seen.set(createHash("sha256").update(source).digest("hex"),file);seen.set(shadowFingerprint(source),file);}const collisions=[];for(const c of CANDIDATES){const p=join(OVERLAY_ROOT,c.file);assert.ok(existsSync(p),`${c.file} must exist`);const source=readFileSync(p,"utf8");for(const [kind,fp] of [["exact duplicate",createHash("sha256").update(source).digest("hex")],["template shadow",shadowFingerprint(source)]]){if(seen.has(fp))collisions.push(`${c.file} ${kind} of ${seen.get(fp)}`);seen.set(fp,c.file);}}assert.deepEqual(collisions,[]);});
  it("parses, effect-checks, emits GIR and executes every decision core",async()=>{for(const c of CANDIDATES){const source=readFileSync(join(OVERLAY_ROOT,c.file),"utf8"),program=parseProgram(source,c.file);assert.deepEqual((program.diagnostics??[]).filter(d=>d.severity==="error"),[],c.file);const effects=checkEffects(program.flows,program.ast);assert.deepEqual(effects.flatMap(r=>r.diagnostics).filter(d=>d.severity==="error"),[],c.file);assert.equal(emitGIR(program.ast,program.flows,effects).gir.flows.length,1,c.file);assert.deepEqual((await executeFlow(c.flow,c.input,program.ast,program.flows)).value,c.expected,c.file);}});
});
