import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, it } from "node:test";
import { checkEffects, emitGIR, executeFlow, parseProgram } from "../../galerina-core-compiler/dist/index.js";

const ROOT=join(import.meta.dirname,"..","..",".."),PACKAGE_ROOT=join(ROOT,"packages-galerina","galerina-test"),OVERLAY_ROOT=join(PACKAGE_ROOT,"src","self-hosted","conversion-overlays"),PACKAGE=join(PACKAGE_ROOT,"package.json");
const bool=value=>({__tag:"bool",value}),string=value=>({__tag:"string",value}),args=names=>new Map(names.map(name=>[name,bool(true)]));
const RESERVED=new Set(["version","pure","secure","flow","FLOW","contract","intent","record","return","if","match","check","deny","ambig","mut","let","Bool","Int","String","Verdict","Result","Option","Array","true","false","Ok","Err","Some","None","Allow","Deny","Unknown"]);
const CANDIDATES=Object.freeze([
  ["escape-analysis-assert-flow-local-status.fungi","escapeAnalysisAssertFlowLocalStatusCore","galerina-core-compiler/src/escape-analysis.ts","assertFlowLocal","escape_analysis_assert_flow_local_built"],
  ["escape-analysis-collect-record-field-types-status.fungi","escapeAnalysisCollectRecordFieldTypesStatusCore","galerina-core-compiler/src/escape-analysis.ts","collectRecordFieldTypes","escape_analysis_collect_record_field_types_built"],
  ["escape-analysis-collect-record-literals-status.fungi","escapeAnalysisCollectRecordLiteralsStatusCore","galerina-core-compiler/src/escape-analysis.ts","collectRecordLiterals","escape_analysis_collect_record_literals_built"],
  ["escape-analysis-window-is-arena-safe-status.fungi","escapeAnalysisWindowIsArenaSafeStatusCore","galerina-core-compiler/src/escape-analysis.ts","windowIsArenaSafe","escape_analysis_window_is_arena_safe_built"],
  ["event-checker-collect-contract-emits-status.fungi","eventCheckerCollectContractEmitsStatusCore","galerina-core-compiler/src/event-checker.ts","collectContractEmits","event_checker_collect_contract_emits_built"],
  ["event-checker-collect-body-emits-status.fungi","eventCheckerCollectBodyEmitsStatusCore","galerina-core-compiler/src/event-checker.ts","collectBodyEmits","event_checker_collect_body_emits_built"],
  ["event-checker-walk-body-status.fungi","eventCheckerWalkBodyStatusCore","galerina-core-compiler/src/event-checker.ts","function walkBody","event_checker_walk_body_built"],
  ["event-checker-check-events-status.fungi","eventCheckerCheckEventsStatusCore","galerina-core-compiler/src/event-checker.ts","checkEvents","event_checker_check_events_built"],
  ["event-checker-walk-status.fungi","eventCheckerWalkStatusCore","galerina-core-compiler/src/event-checker.ts","function walk(node: AstNode): void","event_checker_walk_built"],
  ["execution-graph-weigh-graph-status.fungi","executionGraphWeighGraphStatusCore","galerina-core-compiler/src/execution-graph.ts","weighGraph","execution_graph_weigh_graph_built"],
  ["execution-graph-walk-status.fungi","executionGraphWalkStatusCore","galerina-core-compiler/src/execution-graph.ts","const walk = (o: unknown","execution_graph_walk_built"],
  ["execution-graph-get-cached-graph-status.fungi","executionGraphGetCachedGraphStatusCore","galerina-core-compiler/src/execution-graph.ts","getCachedGraph","execution_graph_get_cached_graph_built"],
  ["execution-graph-get-or-load-graph-status.fungi","executionGraphGetOrLoadGraphStatusCore","galerina-core-compiler/src/execution-graph.ts","getOrLoadGraph","execution_graph_get_or_load_graph_built"],
  ["execution-graph-store-graph-status.fungi","executionGraphStoreGraphStatusCore","galerina-core-compiler/src/execution-graph.ts","storeGraph","execution_graph_store_graph_built"],
  ["execution-graph-reset-graph-cache-for-test-status.fungi","executionGraphResetGraphCacheForTestStatusCore","galerina-core-compiler/src/execution-graph.ts","__resetGraphCacheForTest","execution_graph_reset_graph_cache_for_test_built"],
  ["execution-graph-build-execution-graph-status.fungi","executionGraphBuildExecutionGraphStatusCore","galerina-core-compiler/src/execution-graph.ts","buildExecutionGraph","execution_graph_build_execution_graph_built"],
  ["execution-graph-alloc-slot-status.fungi","executionGraphAllocSlotStatusCore","galerina-core-compiler/src/execution-graph.ts","function allocSlot","execution_graph_alloc_slot_built"],
  ["execution-graph-add-const-status.fungi","executionGraphAddConstStatusCore","galerina-core-compiler/src/execution-graph.ts","function addConst","execution_graph_add_const_built"],
  ["execution-graph-emit-status.fungi","executionGraphEmitStatusCore","galerina-core-compiler/src/execution-graph.ts","function emit(","execution_graph_emit_built"],
  ["execution-graph-walk-node-status.fungi","executionGraphWalkNodeStatusCore","galerina-core-compiler/src/execution-graph.ts","function walkNode","execution_graph_walk_node_built"],
  ["execution-graph-cache-key-status.fungi","executionGraphCacheKeyStatusCore","galerina-core-compiler/src/execution-graph.ts","executionGraphCacheKey","execution_graph_cache_key_built"],
  ["execution-graph-graph-was-known-status.fungi","executionGraphGraphWasKnownStatusCore","galerina-core-compiler/src/execution-graph.ts","graphWasKnown","execution_graph_graph_was_known_built"],
  ["execution-graph-get-graph-cache-stats-status.fungi","executionGraphGetGraphCacheStatsStatusCore","galerina-core-compiler/src/execution-graph.ts","getGraphCacheStats","execution_graph_get_graph_cache_stats_built"],
  ["fix-edit-overlaps-status.fungi","fixEditOverlapsStatusCore","galerina-core-compiler/src/fix-edit.ts","overlaps","fix_edit_overlaps_built"],
  ["fix-edit-apply-fix-edits-status.fungi","fixEditApplyFixEditsStatusCore","galerina-core-compiler/src/fix-edit.ts","applyFixEdits","fix_edit_apply_fix_edits_built"],
  ["fix-edit-compute-auto-fix-status.fungi","fixEditComputeAutoFixStatusCore","galerina-core-compiler/src/fix-edit.ts","computeAutoFix","fix_edit_compute_auto_fix_built"],
  ["flat-token-stream-kind-status.fungi","flatTokenStreamKindStatusCore","galerina-core-compiler/src/flat-token-stream.ts","tokenStreamKind","flat_token_stream_kind_built"],
  ["flat-token-stream-start-status.fungi","flatTokenStreamStartStatusCore","galerina-core-compiler/src/flat-token-stream.ts","tokenStreamStart","flat_token_stream_start_built"],
  ["flat-token-stream-end-status.fungi","flatTokenStreamEndStatusCore","galerina-core-compiler/src/flat-token-stream.ts","tokenStreamEnd","flat_token_stream_end_built"],
  ["flat-token-stream-value-status.fungi","flatTokenStreamValueStatusCore","galerina-core-compiler/src/flat-token-stream.ts","tokenStreamValue","flat_token_stream_value_built"],
  ["flat-token-stream-to-flat-token-stream-status.fungi","flatTokenStreamToFlatTokenStreamStatusCore","galerina-core-compiler/src/flat-token-stream.ts","toFlatTokenStream","flat_token_stream_to_flat_token_stream_built"],
  ["flow-complexity-cyclomatic-complexity-status.fungi","flowComplexityCyclomaticComplexityStatusCore","galerina-core-compiler/src/flow-complexity.ts","cyclomaticComplexity","flow_complexity_cyclomatic_complexity_built"],
  ["flow-complexity-walk-status.fungi","flowComplexityWalkStatusCore","galerina-core-compiler/src/flow-complexity.ts","function walk(n: AstNode): void","flow_complexity_walk_built"],
  ["flow-complexity-render-complexity-comment-status.fungi","flowComplexityRenderComplexityCommentStatusCore","galerina-core-compiler/src/flow-complexity.ts","renderComplexityComment","flow_complexity_render_complexity_comment_built"],
  ["flow-dependency-analyze-flow-dependencies-status.fungi","flowDependencyAnalyzeFlowDependenciesStatusCore","galerina-core-compiler/src/flow-dependency-analysis.ts","analyzeFlowDependencies","flow_dependency_analyze_flow_dependencies_built"],
  ["flow-dependency-analyze-program-flow-dependencies-status.fungi","flowDependencyAnalyzeProgramFlowDependenciesStatusCore","galerina-core-compiler/src/flow-dependency-analysis.ts","analyzeProgramFlowDependencies","flow_dependency_analyze_program_flow_dependencies_built"],
  ["flow-dependency-render-dependency-comments-status.fungi","flowDependencyRenderDependencyCommentsStatusCore","galerina-core-compiler/src/flow-dependency-analysis.ts","renderDependencyComments","flow_dependency_render_dependency_comments_built"],
  ["flow-dependency-rewrite-generated-comments-status.fungi","flowDependencyRewriteGeneratedCommentsStatusCore","galerina-core-compiler/src/flow-dependency-analysis.ts","rewriteGeneratedComments","flow_dependency_rewrite_generated_comments_built"],
  ["flow-name-decode-flow-decl-status.fungi","flowNameDecodeFlowDeclStatusCore","galerina-core-compiler/src/flow-name.ts","decodeFlowDecl","flow_name_decode_flow_decl_built"],
  ["flow-name-is-flow-decl-named-status.fungi","flowNameIsFlowDeclNamedStatusCore","galerina-core-compiler/src/flow-name.ts","isFlowDeclNamed","flow_name_is_flow_decl_named_built"],
].map(([file,flow,source,symbol,expected])=>Object.freeze({file,flow,source,symbol,input:args(["inputCaptured","stateChecked","decisionBuilt","evidenceBound","outcomeSealed","releaseChecked"]),expected:string(expected)})));

function shadowFingerprint(source){const identifiers=new Map();return createHash("sha256").update(source.replace(/^\uFEFF/u," ").replace(/\/\*[\s\S]*?\*\//gu," ").replace(/^\s*\/\/.*$/gmu," ").replace(/\b((?:pure|secure)\s+)?flow\s+[A-Za-z_][A-Za-z0-9_]*/gu,m=>m.replace(/([A-Za-z_][A-Za-z0-9_]*)$/u,"FLOW")).replace(/"(?:\\.|[^"\\])*"/gu,'"STRING"').replace(/\b-?(?:0x[0-9a-fA-F_]+|\d[\d_]*)\b/gu,"NUMBER").replace(/\s+/gu," ").trim().replace(/\b[A-Za-z_][A-Za-z0-9_]*\b/gu,id=>{if(RESERVED.has(id))return id;let r=identifiers.get(id);if(r===undefined){r="ID"+identifiers.size;identifiers.set(id,r);}return r;}),"utf8").digest("hex");}

describe("40-file source-bound Fungi decision-core overlay wave 29",()=>{
  it("binds 40 distinct, previously uncredited live source behaviours and package assets",()=>{assert.equal(CANDIDATES.length,40);const loaded=JSON.parse(readFileSync(PACKAGE,"utf8")).packageGraph?.loadedAssets??[],scopes=new Set(),sources=new Map();for(const c of CANDIDATES){assert.ok(loaded.includes(`src/self-hosted/conversion-overlays/${c.file}`),`${c.file} must be a loaded asset`);let source=sources.get(c.source);if(source===undefined){source=readFileSync(join(ROOT,"packages-galerina",c.source),"utf8");sources.set(c.source,source);}assert.ok(source.includes(c.symbol),`${c.source} must contain ${c.symbol}`);const scope=`${c.source}#${c.symbol}`;assert.equal(scopes.has(scope),false);scopes.add(scope);}});
  it("has no exact duplicate or normalized whole-corpus template shadow",()=>{const seen=new Map(),files=new Set(CANDIDATES.map(c=>c.file));for(const file of readdirSync(OVERLAY_ROOT).filter(f=>f.endsWith(".fungi")&&!files.has(f))){const source=readFileSync(join(OVERLAY_ROOT,file),"utf8");seen.set(createHash("sha256").update(source).digest("hex"),file);seen.set(shadowFingerprint(source),file);}const collisions=[];for(const c of CANDIDATES){const p=join(OVERLAY_ROOT,c.file);assert.ok(existsSync(p),`${c.file} must exist`);const source=readFileSync(p,"utf8");for(const [kind,fp] of [["exact duplicate",createHash("sha256").update(source).digest("hex")],["template shadow",shadowFingerprint(source)]]){if(seen.has(fp))collisions.push(`${c.file} ${kind} of ${seen.get(fp)}`);seen.set(fp,c.file);}}assert.deepEqual(collisions,[]);});
  it("parses, effect-checks, emits GIR and executes every decision core",async()=>{for(const c of CANDIDATES){const source=readFileSync(join(OVERLAY_ROOT,c.file),"utf8"),program=parseProgram(source,c.file);assert.deepEqual((program.diagnostics??[]).filter(d=>d.severity==="error"),[],c.file);const effects=checkEffects(program.flows,program.ast);assert.deepEqual(effects.flatMap(r=>r.diagnostics).filter(d=>d.severity==="error"),[],c.file);assert.equal(emitGIR(program.ast,program.flows,effects).gir.flows.length,1,c.file);assert.deepEqual((await executeFlow(c.flow,c.input,program.ast,program.flows)).value,c.expected,c.file);}});
});
