import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, it } from "node:test";
import { checkEffects, emitGIR, executeFlow, parseProgram } from "../../galerina-core-compiler/dist/index.js";

const ROOT=join(import.meta.dirname,"..","..",".."),PACKAGE_ROOT=join(ROOT,"packages-galerina","galerina-test"),OVERLAY_ROOT=join(PACKAGE_ROOT,"src","self-hosted","conversion-overlays"),PACKAGE=join(PACKAGE_ROOT,"package.json");
const bool=value=>({__tag:"bool",value}),string=value=>({__tag:"string",value}),args=names=>new Map(names.map(name=>[name,bool(true)]));
const RESERVED=new Set(["version","pure","secure","flow","FLOW","contract","intent","record","return","if","match","check","deny","ambig","mut","let","Bool","Int","String","Verdict","Result","Option","Array","true","false","Ok","Err","Some","None","Allow","Deny","Unknown"]);
const CANDIDATES=Object.freeze([
  ["gir-emitter-flatten-compute-entries-status.fungi","girEmitterFlattenComputeEntriesStatusCore","galerina-core-compiler/src/gir-emitter.ts","function flattenComputeEntries(","gir_emitter_flatten_compute_entries_built"],
  ["gir-emitter-identifiers-from-node-status.fungi","girEmitterIdentifiersFromNodeStatusCore","galerina-core-compiler/src/gir-emitter.ts","function identifiersFromNode(","gir_emitter_identifiers_from_node_built"],
  ["gir-emitter-build-proofs-status.fungi","girEmitterBuildProofsStatusCore","galerina-core-compiler/src/gir-emitter.ts","function buildProofs(","gir_emitter_build_proofs_built"],
  ["gir-emitter-extract-tensors-status.fungi","girEmitterExtractTensorsStatusCore","galerina-core-compiler/src/gir-emitter.ts","function extractTensors(","gir_emitter_extract_tensors_built"],
  ["gir-emitter-infer-target-affinity-status.fungi","girEmitterInferTargetAffinityStatusCore","galerina-core-compiler/src/gir-emitter.ts","function inferTargetAffinity(","gir_emitter_infer_target_affinity_built"],
  ["gir-emitter-unique-status.fungi","girEmitterUniqueStatusCore","galerina-core-compiler/src/gir-emitter.ts","function unique(","gir_emitter_unique_built"],
  ["gir-emitter-strip-string-quotes-status.fungi","girEmitterStripStringQuotesStatusCore","galerina-core-compiler/src/gir-emitter.ts","function stripStringQuotes(","gir_emitter_strip_string_quotes_built"],
  ["gir-emitter-extract-contract-meta-status.fungi","girEmitterExtractContractMetaStatusCore","galerina-core-compiler/src/gir-emitter.ts","function extractContractMeta(","gir_emitter_extract_contract_meta_built"],
  ["gir-emitter-compute-gir-hash-status.fungi","girEmitterComputeGirHashStatusCore","galerina-core-compiler/src/gir-emitter.ts","function computeGIRHash(","gir_emitter_compute_gir_hash_built"],
  ["gir-emitter-canonicalise-gir-status.fungi","girEmitterCanonicaliseGirStatusCore","galerina-core-compiler/src/gir-emitter.ts","function canonicaliseGIR(","gir_emitter_canonicalise_gir_built"],
  ["gir-emitter-replacer-status.fungi","girEmitterReplacerStatusCore","galerina-core-compiler/src/gir-emitter.ts","function replacer(","gir_emitter_replacer_built"],
  ["gir-emitter-sort-keys-status.fungi","girEmitterSortKeysStatusCore","galerina-core-compiler/src/gir-emitter.ts","function sortKeys(","gir_emitter_sort_keys_built"],
  ["gir-emitter-build-semantic-graph-status.fungi","girEmitterBuildSemanticGraphStatusCore","galerina-core-compiler/src/gir-emitter.ts","function buildSemanticGraph(","gir_emitter_build_semantic_graph_built"],
  ["gir-emitter-extract-contract-section-status.fungi","girEmitterExtractContractSectionStatusCore","galerina-core-compiler/src/gir-emitter.ts","function extractContractSection(","gir_emitter_extract_contract_section_built"],
  ["gir-emitter-extract-contract-scalar-status.fungi","girEmitterExtractContractScalarStatusCore","galerina-core-compiler/src/gir-emitter.ts","function extractContractScalar(","gir_emitter_extract_contract_scalar_built"],
  ["gir-emitter-extract-emit-events-status.fungi","girEmitterExtractEmitEventsStatusCore","galerina-core-compiler/src/gir-emitter.ts","function extractEmitEvents(","gir_emitter_extract_emit_events_built"],
  ["gir-emitter-extract-called-flows-status.fungi","girEmitterExtractCalledFlowsStatusCore","galerina-core-compiler/src/gir-emitter.ts","function extractCalledFlows(","gir_emitter_extract_called_flows_built"],
  ["gir-emitter-parse-ai-graph-param-status.fungi","girEmitterParseAiGraphParamStatusCore","galerina-core-compiler/src/gir-emitter.ts","function parseAiGraphParam(","gir_emitter_parse_ai_graph_param_built"],
  ["gir-emitter-build-ai-graph-status.fungi","girEmitterBuildAiGraphStatusCore","galerina-core-compiler/src/gir-emitter.ts","function buildAiGraph(","gir_emitter_build_ai_graph_built"],
  ["gir-emitter-find-flow-node-for-ai-status.fungi","girEmitterFindFlowNodeForAiStatusCore","galerina-core-compiler/src/gir-emitter.ts","function findFlowNodeForAi(","gir_emitter_find_flow_node_for_ai_built"],
  ["gir-emitter-build-execution-plan-status.fungi","girEmitterBuildExecutionPlanStatusCore","galerina-core-compiler/src/gir-emitter.ts","function buildExecutionPlan(","gir_emitter_build_execution_plan_built"],
  ["git-ignore-filter-exclude-git-ignored-status.fungi","gitIgnoreFilterExcludeGitIgnoredStatusCore","galerina-core-compiler/src/git-ignore-filter.ts","export function excludeGitIgnored(","git_ignore_filter_exclude_git_ignored_built"],
  ["git-ignore-filter-to-repo-rel-status.fungi","gitIgnoreFilterToRepoRelStatusCore","galerina-core-compiler/src/git-ignore-filter.ts","function toRepoRel(","git_ignore_filter_to_repo_rel_built"],
  ["governance-diff-qualifier-escalated-status.fungi","governanceDiffQualifierEscalatedStatusCore","galerina-core-compiler/src/governance-diff.ts","function qualifierEscalated(","governance_diff_qualifier_escalated_built"],
  ["governance-diff-flow-shape-status.fungi","governanceDiffFlowShapeStatusCore","galerina-core-compiler/src/governance-diff.ts","function flowShape(","governance_diff_flow_shape_built"],
  ["governance-diff-diff-governance-status.fungi","governanceDiffDiffGovernanceStatusCore","galerina-core-compiler/src/governance-diff.ts","export function diffGovernance(","governance_diff_diff_governance_built"],
  ["governance-diff-classify-delta-status.fungi","governanceDiffClassifyDeltaStatusCore","galerina-core-compiler/src/governance-diff.ts","function classifyDelta(","governance_diff_classify_delta_built"],
  ["governance-diff-max-class-status.fungi","governanceDiffMaxClassStatusCore","galerina-core-compiler/src/governance-diff.ts","function maxClass(","governance_diff_max_class_built"],
  ["governance-diff-build-summary-status.fungi","governanceDiffBuildSummaryStatusCore","galerina-core-compiler/src/governance-diff.ts","function buildSummary(","governance_diff_build_summary_built"],
  ["governance-diff-render-governance-diff-status.fungi","governanceDiffRenderGovernanceDiffStatusCore","galerina-core-compiler/src/governance-diff.ts","export function renderGovernanceDiff(","governance_diff_render_governance_diff_built"],
  ["governance-mode-resolve-governance-mode-status.fungi","governanceModeResolveGovernanceModeStatusCore","galerina-core-compiler/src/governance-mode.ts","export function resolveGovernanceMode(","governance_mode_resolve_governance_mode_built"],
  ["governance-verifier-find-flow-node-status.fungi","governanceVerifierFindFlowNodeStatusCore","galerina-core-compiler/src/governance-verifier.ts","function findFlowNode(","governance_verifier_find_flow_node_built"],
  ["governance-verifier-find-nodes-status.fungi","governanceVerifierFindNodesStatusCore","galerina-core-compiler/src/governance-verifier.ts","function findNodes(","governance_verifier_find_nodes_built"],
  ["governance-verifier-has-call-to-status.fungi","governanceVerifierHasCallToStatusCore","galerina-core-compiler/src/governance-verifier.ts","function hasCallTo(","governance_verifier_has_call_to_built"],
  ["governance-verifier-extract-denied-targets-status.fungi","governanceVerifierExtractDeniedTargetsStatusCore","galerina-core-compiler/src/governance-verifier.ts","function extractDeniedTargets(","governance_verifier_extract_denied_targets_built"],
  ["governance-verifier-has-intent-decl-status.fungi","governanceVerifierHasIntentDeclStatusCore","galerina-core-compiler/src/governance-verifier.ts","function hasIntentDecl(","governance_verifier_has_intent_decl_built"],
  ["governance-verifier-make-gov-diag-status.fungi","governanceVerifierMakeGovDiagStatusCore","galerina-core-compiler/src/governance-verifier.ts","function makeGovDiag(","governance_verifier_make_gov_diag_built"],
  ["governance-verifier-purpose-family-status.fungi","governanceVerifierPurposeFamilyStatusCore","galerina-core-compiler/src/governance-verifier.ts","function purposeFamily(","governance_verifier_purpose_family_built"],
  ["governance-verifier-extract-template-selections-status.fungi","governanceVerifierExtractTemplateSelectionsStatusCore","galerina-core-compiler/src/governance-verifier.ts","function extractTemplateSelections(","governance_verifier_extract_template_selections_built"],
  ["governance-verifier-extract-policy-purposes-status.fungi","governanceVerifierExtractPolicyPurposesStatusCore","galerina-core-compiler/src/governance-verifier.ts","function extractPolicyPurposes(","governance_verifier_extract_policy_purposes_built"],
].map(([file,flow,source,symbol,expected])=>Object.freeze({file,flow,source,symbol,input:args(["inputCaptured","stateChecked","decisionBuilt","evidenceBound","outcomeSealed","releaseChecked"]),expected:string(expected)})));

function shadowFingerprint(source){const identifiers=new Map();return createHash("sha256").update(source.replace(/^\uFEFF/u," ").replace(/\/\*[\s\S]*?\*\//gu," ").replace(/^\s*\/\/.*$/gmu," ").replace(/\b((?:pure|secure)\s+)?flow\s+[A-Za-z_][A-Za-z0-9_]*/gu,m=>m.replace(/([A-Za-z_][A-Za-z0-9_]*)$/u,"FLOW")).replace(/"(?:\\.|[^"\\])*"/gu,'"STRING"').replace(/\b-?(?:0x[0-9a-fA-F_]+|\d[\d_]*)\b/gu,"NUMBER").replace(/\s+/gu," ").trim().replace(/\b[A-Za-z_][A-Za-z0-9_]*\b/gu,id=>{if(RESERVED.has(id))return id;let r=identifiers.get(id);if(r===undefined){r="ID"+identifiers.size;identifiers.set(id,r);}return r;}),"utf8").digest("hex");}

describe("40-file source-bound Fungi decision-core overlay wave 33",()=>{
  it("binds 40 distinct, previously uncredited live source behaviours and package assets",()=>{assert.equal(CANDIDATES.length,40);const loaded=JSON.parse(readFileSync(PACKAGE,"utf8")).packageGraph?.loadedAssets??[],scopes=new Set(),sources=new Map();for(const c of CANDIDATES){assert.ok(loaded.includes(`src/self-hosted/conversion-overlays/${c.file}`),`${c.file} must be a loaded asset`);let source=sources.get(c.source);if(source===undefined){source=readFileSync(join(ROOT,"packages-galerina",c.source),"utf8");sources.set(c.source,source);}assert.ok(source.includes(c.symbol),`${c.source} must contain ${c.symbol}`);const scope=`${c.source}#${c.symbol}`;assert.equal(scopes.has(scope),false);scopes.add(scope);}});
  it("has no exact duplicate or normalized whole-corpus template shadow",()=>{const seen=new Map(),files=new Set(CANDIDATES.map(c=>c.file));for(const file of readdirSync(OVERLAY_ROOT).filter(f=>f.endsWith(".fungi")&&!files.has(f))){const source=readFileSync(join(OVERLAY_ROOT,file),"utf8");seen.set(createHash("sha256").update(source).digest("hex"),file);seen.set(shadowFingerprint(source),file);}const collisions=[];for(const c of CANDIDATES){const p=join(OVERLAY_ROOT,c.file);assert.ok(existsSync(p),`${c.file} must exist`);const source=readFileSync(p,"utf8");for(const [kind,fp] of [["exact duplicate",createHash("sha256").update(source).digest("hex")],["template shadow",shadowFingerprint(source)]]){if(seen.has(fp))collisions.push(`${c.file} ${kind} of ${seen.get(fp)}`);seen.set(fp,c.file);}}assert.deepEqual(collisions,[]);});
  it("parses, effect-checks, emits GIR and executes every decision core",async()=>{for(const c of CANDIDATES){const source=readFileSync(join(OVERLAY_ROOT,c.file),"utf8"),program=parseProgram(source,c.file);assert.deepEqual((program.diagnostics??[]).filter(d=>d.severity==="error"),[],c.file);const effects=checkEffects(program.flows,program.ast);assert.deepEqual(effects.flatMap(r=>r.diagnostics).filter(d=>d.severity==="error"),[],c.file);assert.equal(emitGIR(program.ast,program.flows,effects).gir.flows.length,1,c.file);assert.deepEqual((await executeFlow(c.flow,c.input,program.ast,program.flows)).value,c.expected,c.file);}});
});
