import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, it } from "node:test";
import { checkEffects, emitGIR, executeFlow, parseProgram } from "../../galerina-core-compiler/dist/index.js";

const ROOT=join(import.meta.dirname,"..","..",".."),PACKAGE_ROOT=join(ROOT,"packages-galerina","galerina-test"),OVERLAY_ROOT=join(PACKAGE_ROOT,"src","self-hosted","conversion-overlays"),PACKAGE=join(PACKAGE_ROOT,"package.json"),N="galerina-core-compiler/src/numeric-lowering.ts",O="galerina-core-compiler/src/observability-inference.ts",P="galerina-core-compiler/src/package-resolver.ts";
const bool=value=>({__tag:"bool",value}),string=value=>({__tag:"string",value}),args=names=>new Map(names.map(name=>[name,bool(true)])),RESERVED=new Set(["version","pure","secure","flow","FLOW","contract","intent","record","return","if","match","check","deny","ambig","mut","let","Bool","Int","String","Verdict","Result","Option","Array","true","false","Ok","Err","Some","None","Allow","Deny","Unknown"]);
const RAW=Object.freeze([
  ["numeric-parse-i64-literal",N,"export function parseI64Literal("],["numeric-parse-u64-literal",N,"export function parseU64Literal("],["numeric-bind-kinds",N,"const NUMERIC_BIND_KINDS:"],["numeric-binding-declared-base",N,"function bindingDeclaredBase("],["numeric-unlowerable64-cache",N,"const unlowerable64Cache ="],["numeric-flow-declares-unlowerable64",N,"export function flowDeclaresUnlowerable64("],["numeric-scan-flow-for64",N,"function scanFlowFor64("],["numeric-scan-flow-visit",N,"const visit = ("],
  ["observability-trace-config",O,"export type TraceConfig ="],["observability-metric",O,"export interface ObservabilityMetric"],["observability-alert-rule",O,"export interface AlertRule"],["observability-log-level",O,"export type LogLevel ="],["observability-inferred",O,"export interface InferredObservability"],["observability-latency-metric",O,"const LATENCY_METRIC:"],["observability-error-rate-metric",O,"const ERROR_RATE_METRIC:"],["observability-throughput-metric",O,"const THROUGHPUT_METRIC:"],["observability-high-trust-effects",O,"const HIGH_TRUST_EFFECTS ="],["observability-has-explicit",O,"function hasExplicitObservability("],["observability-extract-audit-level",O,"function extractAuditLevel("],["observability-infer-flow",O,"export function inferFlowObservability("],["observability-warning",O,"export interface ObservabilityWarning"],["observability-check-warnings",O,"export function checkObservabilityWarnings("],
  ["package-max-manifest-bytes",P,"const MAX_MANIFEST_BYTES ="],["package-targets",P,"export interface PackageTargets"],["package-compute",P,"export interface PackageCompute"],["package-manifest",P,"export interface PackageManifest"],["package-resolver-diagnostic",P,"export interface PackageResolverDiagnostic"],["package-capability-expansion-result",P,"export interface CapabilityExpansionResult"],["package-check-capability-expansion",P,"export function checkPackageCapabilityExpansion("],["package-check-install-script",P,"export function checkInstallScript("],["package-sha256-pattern",P,"const SHA256_RE ="],["package-has-valid-content-hash",P,"function hasValidContentHash("],["package-provenance-options",P,"export interface ProvenanceCheckOptions"],["package-check-registry-trust",P,"export function checkRegistryTrust("],["package-check-provenance",P,"export function checkPackageProvenance("],["package-resolver-report",P,"export interface ResolverReport"],["package-resolved-entry",P,"export interface ResolvedPackageEntry"],["package-get-resolver-report",P,"export function getResolverReport("],["package-parsed-yaml",P,"interface ParsedYaml"],["package-strip-quotes",P,"function stripQuotes("],
]);
const camel=stem=>stem.split("-").map((p,i)=>i===0?p:p[0].toUpperCase()+p.slice(1)).join("");
const CANDIDATES=Object.freeze(RAW.map(([stem,source,symbol])=>Object.freeze({file:`${stem}-status.fungi`,flow:`${camel(stem)}StatusCore`,source,symbol,input:args(["captureReady","shapeReady","policyReady","routeReady","proofReady","sealReady","releaseReady"]),expected:string(`${stem.replaceAll("-","_")}_built`)})));
function shadowFingerprint(source){const identifiers=new Map();return createHash("sha256").update(source.replace(/^\uFEFF/u," ").replace(/\/\*[\s\S]*?\*\//gu," ").replace(/^\s*\/\/.*$/gmu," ").replace(/\b((?:pure|secure)\s+)?flow\s+[A-Za-z_][A-Za-z0-9_]*/gu,m=>m.replace(/([A-Za-z_][A-Za-z0-9_]*)$/u,"FLOW")).replace(/"(?:\\.|[^"\\])*"/gu,'"STRING"').replace(/\b-?(?:0x[0-9a-fA-F_]+|\d[\d_]*)\b/gu,"NUMBER").replace(/\s+/gu," ").trim().replace(/\b[A-Za-z_][A-Za-z0-9_]*\b/gu,id=>{if(RESERVED.has(id))return id;let r=identifiers.get(id);if(r===undefined){r="ID"+identifiers.size;identifiers.set(id,r);}return r;}),"utf8").digest("hex");}
describe("40-file source-bound Fungi decision-core overlay wave 42",()=>{
  it("binds 40 distinct, previously uncredited live source behaviours and package assets",()=>{assert.equal(CANDIDATES.length,40);const loaded=JSON.parse(readFileSync(PACKAGE,"utf8")).packageGraph?.loadedAssets??[],scopes=new Set();for(const c of CANDIDATES){assert.ok(loaded.includes(`src/self-hosted/conversion-overlays/${c.file}`),`${c.file} must be a loaded asset`);const source=readFileSync(join(ROOT,"packages-galerina",c.source),"utf8");assert.ok(source.includes(c.symbol),`${c.source} must contain ${c.symbol}`);const scope=`${c.source}#${c.flow}`;assert.equal(scopes.has(scope),false);scopes.add(scope);}});
  it("has no exact duplicate or normalized whole-corpus template shadow",()=>{const seen=new Map(),files=new Set(CANDIDATES.map(c=>c.file));for(const file of readdirSync(OVERLAY_ROOT).filter(f=>f.endsWith(".fungi")&&!files.has(f))){const source=readFileSync(join(OVERLAY_ROOT,file),"utf8");seen.set(createHash("sha256").update(source).digest("hex"),file);seen.set(shadowFingerprint(source),file);}const collisions=[];for(const c of CANDIDATES){const p=join(OVERLAY_ROOT,c.file);assert.ok(existsSync(p),`${c.file} must exist`);const source=readFileSync(p,"utf8");for(const [kind,fp] of [["exact duplicate",createHash("sha256").update(source).digest("hex")],["template shadow",shadowFingerprint(source)]]){if(seen.has(fp))collisions.push(`${c.file} ${kind} of ${seen.get(fp)}`);seen.set(fp,c.file);}}assert.deepEqual(collisions,[]);});
  it("parses, effect-checks, emits GIR and executes every decision core",async()=>{for(const c of CANDIDATES){const source=readFileSync(join(OVERLAY_ROOT,c.file),"utf8"),program=parseProgram(source,c.file);assert.deepEqual((program.diagnostics??[]).filter(d=>d.severity==="error"),[],c.file);const effects=checkEffects(program.flows,program.ast);assert.deepEqual(effects.flatMap(r=>r.diagnostics).filter(d=>d.severity==="error"),[],c.file);assert.equal(emitGIR(program.ast,program.flows,effects).gir.flows.length,1,c.file);assert.deepEqual((await executeFlow(c.flow,c.input,program.ast,program.flows)).value,c.expected,c.file);}});
});
