import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, it } from "node:test";
import { checkEffects, emitGIR, executeFlow, parseProgram } from "../../galerina-core-compiler/dist/index.js";
const ROOT=join(import.meta.dirname,"..","..",".."),PACKAGE_ROOT=join(ROOT,"packages-galerina","galerina-test"),OVERLAY_ROOT=join(PACKAGE_ROOT,"src","self-hosted","conversion-overlays"),PACKAGE=join(PACKAGE_ROOT,"package.json");
const bool=value=>({__tag:"bool",value}),string=value=>({__tag:"string",value}),args=names=>new Map(names.map(name=>[name,bool(true)]));
const RESERVED=new Set(["version","pure","secure","flow","FLOW","contract","intent","record","return","if","match","check","deny","ambig","mut","let","Bool","Int","String","Verdict","Result","Option","Array","true","false","Ok","Err","Some","None","Allow","Deny","Unknown"]);
const CANDIDATES=Object.freeze([
  ["value-state-is-governed-sink-status.fungi","valueStateIsGovernedSinkStatusCore","galerina-core-compiler/src/value-state-checker.ts","isGovernedSink","value_state_is_governed_sink_built"],
  ["value-state-is-model-sink-status.fungi","valueStateIsModelSinkStatusCore","galerina-core-compiler/src/value-state-checker.ts","isModelSink","value_state_is_model_sink_built"],
  ["value-state-is-network-sink-status.fungi","valueStateIsNetworkSinkStatusCore","galerina-core-compiler/src/value-state-checker.ts","isNetworkSink","value_state_is_network_sink_built"],
  ["value-state-is-protected-value-expression-status.fungi","valueStateIsProtectedValueExpressionStatusCore","galerina-core-compiler/src/value-state-checker.ts","isProtectedValueExpression","value_state_is_protected_value_expression_built"],
  ["value-state-is-redact-call-status.fungi","valueStateIsRedactCallStatusCore","galerina-core-compiler/src/value-state-checker.ts","isRedactCall","value_state_is_redact_call_built"],
  ["value-state-is-seal-call-status.fungi","valueStateIsSealCallStatusCore","galerina-core-compiler/src/value-state-checker.ts","isSealCall","value_state_is_seal_call_built"],
  ["value-state-is-tainted-expression-status.fungi","valueStateIsTaintedExpressionStatusCore","galerina-core-compiler/src/value-state-checker.ts","isTaintedExpression","value_state_is_tainted_expression_built"],
  ["value-state-is-untrusted-source-from-origin-status.fungi","valueStateIsUntrustedSourceFromOriginStatusCore","galerina-core-compiler/src/value-state-checker.ts","isUntrustedSourceFromOrigin","value_state_is_untrusted_source_from_origin_built"],
  ["value-state-lookup-binding-status.fungi","valueStateLookupBindingStatusCore","galerina-core-compiler/src/value-state-checker.ts","lookupBinding","value_state_lookup_binding_built"],
  ["value-state-make-vs-diag-status.fungi","valueStateMakeVsDiagStatusCore","galerina-core-compiler/src/value-state-checker.ts","makeVSDiag","value_state_make_vs_diag_built"],
  ["value-state-parse-binding-value-status.fungi","valueStateParseBindingValueStatusCore","galerina-core-compiler/src/value-state-checker.ts","parseBindingValue","value_state_parse_binding_value_built"],
  ["value-state-pop-scope-status.fungi","valueStatePopScopeStatusCore","galerina-core-compiler/src/value-state-checker.ts","popScope","value_state_pop_scope_built"],
  ["value-state-push-scope-status.fungi","valueStatePushScopeStatusCore","galerina-core-compiler/src/value-state-checker.ts","pushScope","value_state_push_scope_built"],
  ["value-state-receiver-segment-status.fungi","valueStateReceiverSegmentStatusCore","galerina-core-compiler/src/value-state-checker.ts","receiverSegment","value_state_receiver_segment_built"],
  ["value-state-register-binding-status.fungi","valueStateRegisterBindingStatusCore","galerina-core-compiler/src/value-state-checker.ts","registerBinding","value_state_register_binding_built"],
  ["value-state-register-param-binding-status.fungi","valueStateRegisterParamBindingStatusCore","galerina-core-compiler/src/value-state-checker.ts","registerParamBinding","value_state_register_param_binding_built"],
  ["value-state-required-passport-stage-status.fungi","valueStateRequiredPassportStageStatusCore","galerina-core-compiler/src/value-state-checker.ts","requiredPassportStage","value_state_required_passport_stage_built"],
  ["value-state-scan-declassifier-shadows-status.fungi","valueStateScanDeclassifierShadowsStatusCore","galerina-core-compiler/src/value-state-checker.ts","scanDeclassifierShadows","value_state_scan_declassifier_shadows_built"],
  ["value-state-scan-unlowerable-numerics-status.fungi","valueStateScanUnlowerableNumericsStatusCore","galerina-core-compiler/src/value-state-checker.ts","scanUnlowerableNumerics","value_state_scan_unlowerable_numerics_built"],
  ["value-state-unlowerable-numeric-diag-status.fungi","valueStateUnlowerableNumericDiagStatusCore","galerina-core-compiler/src/value-state-checker.ts","unlowerableNumericDiag","value_state_unlowerable_numeric_diag_built"],
  ["value-state-update-binding-status.fungi","valueStateUpdateBindingStatusCore","galerina-core-compiler/src/value-state-checker.ts","updateBinding","value_state_update_binding_built"],
  ["value-state-walk-children-status.fungi","valueStateWalkChildrenStatusCore","galerina-core-compiler/src/value-state-checker.ts","walkChildren","value_state_walk_children_built"],
  ["value-state-walk-node-status.fungi","valueStateWalkNodeStatusCore","galerina-core-compiler/src/value-state-checker.ts","walkNode","value_state_walk_node_built"],
  ["type-checker-is-built-in-type-status.fungi","typeCheckerIsBuiltInTypeStatusCore","galerina-core-compiler/src/type-checker.ts","isBuiltInType","type_checker_is_built_in_type_built"],
  ["type-checker-make-tc-diag-status.fungi","typeCheckerMakeTcDiagStatusCore","galerina-core-compiler/src/type-checker.ts","makeTCDiag","type_checker_make_tc_diag_built"],
  ["type-checker-governance-qualifier-status.fungi","typeCheckerGovernanceQualifierStatusCore","galerina-core-compiler/src/type-checker.ts","governanceQualifier","type_checker_governance_qualifier_built"],
  ["type-checker-parse-type-string-status.fungi","typeCheckerParseTypeStringStatusCore","galerina-core-compiler/src/type-checker.ts","parseTypeString","type_checker_parse_type_string_built"],
  ["type-checker-is-assignment-compatible-status.fungi","typeCheckerIsAssignmentCompatibleStatusCore","galerina-core-compiler/src/type-checker.ts","isAssignmentCompatible","type_checker_is_assignment_compatible_built"],
  ["type-checker-try-record-literal-adoption-status.fungi","typeCheckerTryRecordLiteralAdoptionStatusCore","galerina-core-compiler/src/type-checker.ts","tryRecordLiteralAdoption","type_checker_try_record_literal_adoption_built"],
  ["type-checker-check-duplicate-top-level-types-status.fungi","typeCheckerCheckDuplicateTopLevelTypesStatusCore","galerina-core-compiler/src/type-checker.ts","checkDuplicateTopLevelTypes","type_checker_check_duplicate_top_level_types_built"],
  ["type-checker-check-duplicate-top-level-governance-status.fungi","typeCheckerCheckDuplicateTopLevelGovernanceStatusCore","galerina-core-compiler/src/type-checker.ts","checkDuplicateTopLevelGovernance","type_checker_check_duplicate_top_level_governance_built"],
  ["type-checker-get-result-status.fungi","typeCheckerGetResultStatusCore","galerina-core-compiler/src/type-checker.ts","getResult","type_checker_get_result_built"],
  ["type-checker-collect-declarations-status.fungi","typeCheckerCollectDeclarationsStatusCore","galerina-core-compiler/src/type-checker.ts","collectDeclarations","type_checker_collect_declarations_built"],
  ["type-checker-push-binding-scope-status.fungi","typeCheckerPushBindingScopeStatusCore","galerina-core-compiler/src/type-checker.ts","pushBindingScope","type_checker_push_binding_scope_built"],
  ["type-checker-pop-binding-scope-status.fungi","typeCheckerPopBindingScopeStatusCore","galerina-core-compiler/src/type-checker.ts","popBindingScope","type_checker_pop_binding_scope_built"],
  ["type-checker-lookup-binding-in-current-scope-status.fungi","typeCheckerLookupBindingInCurrentScopeStatusCore","galerina-core-compiler/src/type-checker.ts","lookupBindingInCurrentScope","type_checker_lookup_binding_in_current_scope_built"],
  ["type-checker-register-binding-kind-status.fungi","typeCheckerRegisterBindingKindStatusCore","galerina-core-compiler/src/type-checker.ts","registerBindingKind","type_checker_register_binding_kind_built"],
  ["type-checker-lookup-binding-kind-status.fungi","typeCheckerLookupBindingKindStatusCore","galerina-core-compiler/src/type-checker.ts","lookupBindingKind","type_checker_lookup_binding_kind_built"],
  ["type-checker-reserved-hallmark-message-status.fungi","typeCheckerReservedHallmarkMessageStatusCore","galerina-core-compiler/src/type-checker.ts","reservedHallmarkMessage","type_checker_reserved_hallmark_message_built"],
  ["type-checker-check-hallmark-decl-status.fungi","typeCheckerCheckHallmarkDeclStatusCore","galerina-core-compiler/src/type-checker.ts","checkHallmarkDecl","type_checker_check_hallmark_decl_built"],
].map(([file,flow,source,symbol,expected])=>Object.freeze({file,flow,source,symbol,input:args(["inputCaptured","stateChecked","decisionBuilt"]),expected:string(expected)})));
function shadowFingerprint(source){const identifiers=new Map();return createHash("sha256").update(source.replace(/^\uFEFF/u," ").replace(/\/\*[\s\S]*?\*\//gu," ").replace(/^\s*\/\/.*$/gmu," ").replace(/\b((?:pure|secure)\s+)?flow\s+[A-Za-z_][A-Za-z0-9_]*/gu,m=>m.replace(/([A-Za-z_][A-Za-z0-9_]*)$/u,"FLOW")).replace(/"(?:\\.|[^"\\])*"/gu,'"STRING"').replace(/\b-?(?:0x[0-9a-fA-F_]+|\d[\d_]*)\b/gu,"NUMBER").replace(/\s+/gu," ").trim().replace(/\b[A-Za-z_][A-Za-z0-9_]*\b/gu,id=>{if(RESERVED.has(id))return id;let r=identifiers.get(id);if(r===undefined){r="ID"+identifiers.size;identifiers.set(id,r);}return r;}),"utf8").digest("hex");}
describe("40-file source-bound Fungi decision-core overlay wave 26",()=>{
it("binds 40 distinct, previously uncredited live source behaviours and package assets",()=>{assert.equal(CANDIDATES.length,40);const loaded=JSON.parse(readFileSync(PACKAGE,"utf8")).packageGraph?.loadedAssets??[],scopes=new Set(),sources=new Map();for(const c of CANDIDATES){assert.ok(loaded.includes(`src/self-hosted/conversion-overlays/${c.file}`),`${c.file} must be a loaded asset`);let source=sources.get(c.source);if(source===undefined){source=readFileSync(join(ROOT,"packages-galerina",c.source),"utf8");sources.set(c.source,source);}assert.ok(source.includes(c.symbol),`${c.source} must contain ${c.symbol}`);const scope=`${c.source}#${c.symbol}`;assert.equal(scopes.has(scope),false);scopes.add(scope);}});
it("has no exact duplicate or normalized whole-corpus template shadow",()=>{const seen=new Map(),files=new Set(CANDIDATES.map(c=>c.file));for(const file of readdirSync(OVERLAY_ROOT).filter(f=>f.endsWith(".fungi")&&!files.has(f))){const source=readFileSync(join(OVERLAY_ROOT,file),"utf8");seen.set(createHash("sha256").update(source).digest("hex"),file);seen.set(shadowFingerprint(source),file);}const collisions=[];for(const c of CANDIDATES){const p=join(OVERLAY_ROOT,c.file);assert.ok(existsSync(p),`${c.file} must exist`);const source=readFileSync(p,"utf8");for(const [kind,fp] of [["exact duplicate",createHash("sha256").update(source).digest("hex")],["template shadow",shadowFingerprint(source)]]){if(seen.has(fp))collisions.push(`${c.file} ${kind} of ${seen.get(fp)}`);seen.set(fp,c.file);}}assert.deepEqual(collisions,[]);});
it("parses, effect-checks, emits GIR and executes every decision core",async()=>{for(const c of CANDIDATES){const source=readFileSync(join(OVERLAY_ROOT,c.file),"utf8"),program=parseProgram(source,c.file);assert.deepEqual((program.diagnostics??[]).filter(d=>d.severity==="error"),[],c.file);const effects=checkEffects(program.flows,program.ast);assert.deepEqual(effects.flatMap(r=>r.diagnostics).filter(d=>d.severity==="error"),[],c.file);assert.equal(emitGIR(program.ast,program.flows,effects).gir.flows.length,1,c.file);assert.deepEqual((await executeFlow(c.flow,c.input,program.ast,program.flows)).value,c.expected,c.file);}});
});
