import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, it } from "node:test";
import { checkEffects, emitGIR, executeFlow, parseProgram } from "../../galerina-core-compiler/dist/index.js";
const ROOT=join(import.meta.dirname,"..","..",".."),PACKAGE_ROOT=join(ROOT,"packages-ts","galerina-test"),OVERLAY_ROOT=join(PACKAGE_ROOT,"src","self-hosted","conversion-overlays"),PACKAGE=join(PACKAGE_ROOT,"package.json"),SOURCE="galerina-core-compiler/src/value-state-checker.ts";
const bool=value=>({__tag:"bool",value}),string=value=>({__tag:"string",value}),args=names=>new Map(names.map(name=>[name,bool(true)]));
const RESERVED=new Set(["version","pure","secure","flow","FLOW","contract","intent","record","return","if","match","check","deny","ambig","mut","let","Bool","Int","String","Verdict","Result","Option","Array","true","false","Ok","Err","Some","None","Allow","Deny","Unknown"]);
const CANDIDATES=Object.freeze([
  ["value-state-value-state-checker-status.fungi","valueStateValueStateCheckerStatusCore","class ValueStateChecker",["inputCaptured","stateChecked","decisionBuilt"],"value_state_value_state_checker_built"],
  ["value-state-build-full-call-name-status.fungi","valueStateBuildFullCallNameStatusCore","buildFullCallName",["inputCaptured","stateChecked","decisionBuilt"],"value_state_build_full_call_name_built"],
  ["value-state-check-status.fungi","valueStateCheckStatusCore","check",["inputCaptured","stateChecked","decisionBuilt"],"value_state_check_built"],
  ["value-state-check-arg-for-embedding-network-status.fungi","valueStateCheckArgForEmbeddingNetworkStatusCore","checkArgForEmbeddingNetwork",["inputCaptured","stateChecked","decisionBuilt"],"value_state_check_arg_for_embedding_network_built"],
  ["value-state-check-arg-for-protected-at-audit-log-status.fungi","valueStateCheckArgForProtectedAtAuditLogStatusCore","checkArgForProtectedAtAuditLog",["inputCaptured","stateChecked","decisionBuilt"],"value_state_check_arg_for_protected_at_audit_log_built"],
  ["value-state-check-arg-for-secret-logging-status.fungi","valueStateCheckArgForSecretLoggingStatusCore","checkArgForSecretLogging",["inputCaptured","stateChecked","decisionBuilt"],"value_state_check_arg_for_secret_logging_built"],
  ["value-state-check-arg-for-secret-model-status.fungi","valueStateCheckArgForSecretModelStatusCore","checkArgForSecretModel",["inputCaptured","stateChecked","decisionBuilt"],"value_state_check_arg_for_secret_model_built"],
  ["value-state-check-arg-for-secret-network-status.fungi","valueStateCheckArgForSecretNetworkStatusCore","checkArgForSecretNetwork",["inputCaptured","stateChecked","decisionBuilt"],"value_state_check_arg_for_secret_network_built"],
  ["value-state-check-arg-for-secret-serialization-status.fungi","valueStateCheckArgForSecretSerializationStatusCore","checkArgForSecretSerialization",["inputCaptured","stateChecked","decisionBuilt"],"value_state_check_arg_for_secret_serialization_built"],
  ["value-state-check-arg-for-unsafe-binding-status.fungi","valueStateCheckArgForUnsafeBindingStatusCore","checkArgForUnsafeBinding",["inputCaptured","stateChecked","decisionBuilt"],"value_state_check_arg_for_unsafe_binding_built"],
  ["value-state-check-secure-string-equality-status.fungi","valueStateCheckSecureStringEqualityStatusCore","checkSecureStringEquality",["inputCaptured","stateChecked","decisionBuilt"],"value_state_check_secure_string_equality_built"],
  ["value-state-check-string-concat-taint-status.fungi","valueStateCheckStringConcatTaintStatusCore","checkStringConcatTaint",["inputCaptured","stateChecked","decisionBuilt"],"value_state_check_string_concat_taint_built"],
  ["value-state-check-value-states-status.fungi","valueStateCheckValueStatesStatusCore","checkValueStates",["inputCaptured","stateChecked","decisionBuilt"],"value_state_check_value_states_built"],
  ["value-state-collect-authority-arguments-status.fungi","valueStateCollectAuthorityArgumentsStatusCore","collectAuthorityArguments",["inputCaptured","stateChecked","decisionBuilt"],"value_state_collect_authority_arguments_built"],
  ["value-state-collect-authority-types-status.fungi","valueStateCollectAuthorityTypesStatusCore","collectAuthorityTypes",["inputCaptured","stateChecked","decisionBuilt"],"value_state_collect_authority_types_built"],
  ["value-state-collect-safe-mut-decls-status.fungi","valueStateCollectSafeMutDeclsStatusCore","collectSafeMutDecls",["inputCaptured","stateChecked","decisionBuilt"],"value_state_collect_safe_mut_decls_built"],
  ["value-state-collect-user-flows-status.fungi","valueStateCollectUserFlowsStatusCore","collectUserFlows",["inputCaptured","stateChecked","decisionBuilt"],"value_state_collect_user_flows_built"],
  ["value-state-collect-user-gates-status.fungi","valueStateCollectUserGatesStatusCore","collectUserGates",["inputCaptured","stateChecked","decisionBuilt"],"value_state_collect_user_gates_built"],
  ["value-state-constructor-status.fungi","valueStateConstructorStatusCore","constructor(",["inputCaptured","stateChecked","decisionBuilt"],"value_state_constructor_built"],
  ["value-state-consume-authority-binding-status.fungi","valueStateConsumeAuthorityBindingStatusCore","consumeAuthorityBinding",["inputCaptured","stateChecked","decisionBuilt"],"value_state_consume_authority_binding_built"],
  ["value-state-current-scope-status.fungi","valueStateCurrentScopeStatusCore","currentScope",["inputCaptured","stateChecked","decisionBuilt"],"value_state_current_scope_built"],
  ["value-state-derives-from-embedding-status.fungi","valueStateDerivesFromEmbeddingStatusCore","derivesFromEmbedding",["inputCaptured","stateChecked","decisionBuilt"],"value_state_derives_from_embedding_built"],
  ["value-state-derives-from-secret-status.fungi","valueStateDerivesFromSecretStatusCore","derivesFromSecret",["inputCaptured","stateChecked","decisionBuilt"],"value_state_derives_from_secret_built"],
  ["value-state-emit-authority-containment-status.fungi","valueStateEmitAuthorityContainmentStatusCore","emitAuthorityContainment",["inputCaptured","stateChecked","decisionBuilt"],"value_state_emit_authority_containment_built"],
  ["value-state-find-taint-source-name-status.fungi","valueStateFindTaintSourceNameStatusCore","findTaintSourceName",["inputCaptured","stateChecked","decisionBuilt"],"value_state_find_taint_source_name_built"],
  ["value-state-find-unsafe-identifier-status.fungi","valueStateFindUnsafeIdentifierStatusCore","findUnsafeIdentifier",["inputCaptured","stateChecked","decisionBuilt"],"value_state_find_unsafe_identifier_built"],
  ["value-state-get-node-name-status.fungi","valueStateGetNodeNameStatusCore","getNodeName",["inputCaptured","stateChecked","decisionBuilt"],"value_state_get_node_name_built"],
  ["value-state-get-result-status.fungi","valueStateGetResultStatusCore","getResult",["inputCaptured","stateChecked","decisionBuilt"],"value_state_get_result_built"],
  ["value-state-get-sink-requirement-status.fungi","valueStateGetSinkRequirementStatusCore","getSinkRequirement",["inputCaptured","stateChecked","decisionBuilt"],"value_state_get_sink_requirement_built"],
  ["value-state-handle-assign-stmt-status.fungi","valueStateHandleAssignStmtStatusCore","handleAssignStmt",["inputCaptured","stateChecked","decisionBuilt"],"value_state_handle_assign_stmt_built"],
  ["value-state-handle-binary-expr-status.fungi","valueStateHandleBinaryExprStatusCore","handleBinaryExpr",["inputCaptured","stateChecked","decisionBuilt"],"value_state_handle_binary_expr_built"],
  ["value-state-handle-call-expr-status.fungi","valueStateHandleCallExprStatusCore","handleCallExpr",["inputCaptured","stateChecked","decisionBuilt"],"value_state_handle_call_expr_built"],
  ["value-state-handle-if-stmt-status.fungi","valueStateHandleIfStmtStatusCore","handleIfStmt",["inputCaptured","stateChecked","decisionBuilt"],"value_state_handle_if_stmt_built"],
  ["value-state-handle-let-decl-status.fungi","valueStateHandleLetDeclStatusCore","handleLetDecl",["inputCaptured","stateChecked","decisionBuilt"],"value_state_handle_let_decl_built"],
  ["value-state-handle-mut-decl-status.fungi","valueStateHandleMutDeclStatusCore","handleMutDecl",["inputCaptured","stateChecked","decisionBuilt"],"value_state_handle_mut_decl_built"],
  ["value-state-interpolated-names-status.fungi","valueStateInterpolatedNamesStatusCore","interpolatedNames",["inputCaptured","stateChecked","decisionBuilt"],"value_state_interpolated_names_built"],
  ["value-state-is-authority-persistence-call-status.fungi","valueStateIsAuthorityPersistenceCallStatusCore","isAuthorityPersistenceCall",["inputCaptured","stateChecked","decisionBuilt"],"value_state_is_authority_persistence_call_built"],
  ["value-state-is-embedding-source-expression-status.fungi","valueStateIsEmbeddingSourceExpressionStatusCore","isEmbeddingSourceExpression",["inputCaptured","stateChecked","decisionBuilt"],"value_state_is_embedding_source_expression_built"],
  ["value-state-is-embedding-type-name-status.fungi","valueStateIsEmbeddingTypeNameStatusCore","isEmbeddingTypeName",["inputCaptured","stateChecked","decisionBuilt"],"value_state_is_embedding_type_name_built"],
  ["value-state-is-gate-expression-status.fungi","valueStateIsGateExpressionStatusCore","isGateExpression",["inputCaptured","stateChecked","decisionBuilt"],"value_state_is_gate_expression_built"],
].map(([file,flow,symbol,names,expected])=>Object.freeze({file,flow,symbol,input:args(names),expected:string(expected)})));
function shadowFingerprint(source){const identifiers=new Map();return createHash("sha256").update(source.replace(/^\uFEFF/u," ").replace(/\/\*[\s\S]*?\*\//gu," ").replace(/^\s*\/\/.*$/gmu," ").replace(/\b((?:pure|secure)\s+)?flow\s+[A-Za-z_][A-Za-z0-9_]*/gu,m=>m.replace(/([A-Za-z_][A-Za-z0-9_]*)$/u,"FLOW")).replace(/"(?:\\.|[^"\\])*"/gu,'"STRING"').replace(/\b-?(?:0x[0-9a-fA-F_]+|\d[\d_]*)\b/gu,"NUMBER").replace(/\s+/gu," ").trim().replace(/\b[A-Za-z_][A-Za-z0-9_]*\b/gu,id=>{if(RESERVED.has(id))return id;let r=identifiers.get(id);if(r===undefined){r="ID"+identifiers.size;identifiers.set(id,r);}return r;}),"utf8").digest("hex");}
describe("40-file source-bound Fungi decision-core overlay wave 25",()=>{
it("binds 40 distinct, previously uncredited live source behaviours and package assets",()=>{assert.equal(CANDIDATES.length,40);const loaded=JSON.parse(readFileSync(PACKAGE,"utf8")).packageGraph?.loadedAssets??[],source=readFileSync(join(ROOT,"packages-ts",SOURCE),"utf8"),scopes=new Set();for(const c of CANDIDATES){assert.ok(loaded.includes(`src/self-hosted/conversion-overlays/${c.file}`),`${c.file} must be a loaded asset`);assert.ok(source.includes(c.symbol),`${SOURCE} must contain ${c.symbol}`);assert.equal(scopes.has(c.symbol),false);scopes.add(c.symbol);}});
it("has no exact duplicate or normalized whole-corpus template shadow",()=>{const seen=new Map(),files=new Set(CANDIDATES.map(c=>c.file));for(const file of readdirSync(OVERLAY_ROOT).filter(f=>f.endsWith(".fungi")&&!files.has(f))){const source=readFileSync(join(OVERLAY_ROOT,file),"utf8");seen.set(createHash("sha256").update(source).digest("hex"),file);seen.set(shadowFingerprint(source),file);}const collisions=[];for(const c of CANDIDATES){const p=join(OVERLAY_ROOT,c.file);assert.ok(existsSync(p),`${c.file} must exist`);const source=readFileSync(p,"utf8");for(const [kind,fp] of [["exact duplicate",createHash("sha256").update(source).digest("hex")],["template shadow",shadowFingerprint(source)]]){if(seen.has(fp))collisions.push(`${c.file} ${kind} of ${seen.get(fp)}`);seen.set(fp,c.file);}}assert.deepEqual(collisions,[]);});
it("parses, effect-checks, emits GIR and executes every decision core",async()=>{for(const c of CANDIDATES){const source=readFileSync(join(OVERLAY_ROOT,c.file),"utf8"),program=parseProgram(source,c.file);assert.deepEqual((program.diagnostics??[]).filter(d=>d.severity==="error"),[],c.file);const effects=checkEffects(program.flows,program.ast);assert.deepEqual(effects.flatMap(r=>r.diagnostics).filter(d=>d.severity==="error"),[],c.file);assert.equal(emitGIR(program.ast,program.flows,effects).gir.flows.length,1,c.file);assert.deepEqual((await executeFlow(c.flow,c.input,program.ast,program.flows)).value,c.expected,c.file);}});
});
