import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, it } from "node:test";
import { checkEffects, emitGIR, executeFlow, parseProgram } from "../../galerina-core-compiler/dist/index.js";

const ROOT=join(import.meta.dirname,"..","..",".."),PACKAGE_ROOT=join(ROOT,"packages-ts","galerina-test"),OVERLAY_ROOT=join(PACKAGE_ROOT,"src","self-hosted","conversion-overlays"),PACKAGE=join(PACKAGE_ROOT,"package.json");
const bool=value=>({__tag:"bool",value}),string=value=>({__tag:"string",value}),args=names=>new Map(names.map(name=>[name,bool(true)]));
const RESERVED=new Set(["version","pure","secure","flow","FLOW","contract","intent","record","return","if","match","check","deny","ambig","mut","let","Bool","Int","String","Verdict","Result","Option","Array","true","false","Ok","Err","Some","None","Allow","Deny","Unknown"]);
const CANDIDATES=Object.freeze([
  ["effect-checker-broad-effect-for-unknown-effectful-call-status.fungi","effectCheckerBroadEffectForUnknownEffectfulCallStatusCore","galerina-core-compiler/src/effect-checker.ts","broadEffectForUnknownEffectfulCall","effect_checker_broad_effect_for_unknown_effectful_call_built"],
  ["effect-checker-build-call-text-status.fungi","effectCheckerBuildCallTextStatusCore","galerina-core-compiler/src/effect-checker.ts","buildCallText","effect_checker_build_call_text_built"],
  ["effect-checker-build-contract-effects-block-status.fungi","effectCheckerBuildContractEffectsBlockStatusCore","galerina-core-compiler/src/effect-checker.ts","buildContractEffectsBlock","effect_checker_build_contract_effects_block_built"],
  ["effect-checker-build-flow-call-graph-status.fungi","effectCheckerBuildFlowCallGraphStatusCore","galerina-core-compiler/src/effect-checker.ts","buildFlowCallGraph","effect_checker_build_flow_call_graph_built"],
  ["effect-checker-build-flow-effect-summary-status.fungi","effectCheckerBuildFlowEffectSummaryStatusCore","galerina-core-compiler/src/effect-checker.ts","buildFlowEffectSummary","effect_checker_build_flow_effect_summary_built"],
  ["effect-checker-build-module-alias-map-status.fungi","effectCheckerBuildModuleAliasMapStatusCore","galerina-core-compiler/src/effect-checker.ts","buildModuleAliasMap","effect_checker_build_module_alias_map_built"],
  ["effect-checker-check-effects-status.fungi","effectCheckerCheckEffectsStatusCore","galerina-core-compiler/src/effect-checker.ts","checkEffects","effect_checker_check_effects_built"],
  ["effect-checker-check-flow-effects-status.fungi","effectCheckerCheckFlowEffectsStatusCore","galerina-core-compiler/src/effect-checker.ts","checkFlowEffects","effect_checker_check_flow_effects_built"],
  ["effect-checker-check-stdlib-effects-status.fungi","effectCheckerCheckStdlibEffectsStatusCore","galerina-core-compiler/src/effect-checker.ts","checkStdlibEffects","effect_checker_check_stdlib_effects_built"],
  ["effect-checker-collect-status.fungi","effectCheckerCollectStatusCore","galerina-core-compiler/src/effect-checker.ts","function collect(node: AstNode)","effect_checker_collect_built"],
  ["effect-checker-collect-fn-helper-effects-status.fungi","effectCheckerCollectFnHelperEffectsStatusCore","galerina-core-compiler/src/effect-checker.ts","collectFnHelperEffects","effect_checker_collect_fn_helper_effects_built"],
  ["effect-checker-collect-local-bindings-status.fungi","effectCheckerCollectLocalBindingsStatusCore","galerina-core-compiler/src/effect-checker.ts","collectLocalBindings","effect_checker_collect_local_bindings_built"],
  ["effect-checker-collect-transitive-called-effects-status.fungi","effectCheckerCollectTransitiveCalledEffectsStatusCore","galerina-core-compiler/src/effect-checker.ts","collectTransitiveCalledEffects","effect_checker_collect_transitive_called_effects_built"],
  ["effect-checker-effect-edit-distance-status.fungi","effectCheckerEffectEditDistanceStatusCore","galerina-core-compiler/src/effect-checker.ts","effectEditDistance","effect_checker_effect_edit_distance_built"],
  ["effect-checker-effect-results-to-diagnostics-status.fungi","effectCheckerEffectResultsToDiagnosticsStatusCore","galerina-core-compiler/src/effect-checker.ts","effectResultsToDiagnostics","effect_checker_effect_results_to_diagnostics_built"],
  ["effect-checker-find-calls-to-effectful-flows-status.fungi","effectCheckerFindCallsToEffectfulFlowsStatusCore","galerina-core-compiler/src/effect-checker.ts","findCallsToEffectfulFlows","effect_checker_find_calls_to_effectful_flows_built"],
  ["effect-checker-find-direct-flow-calls-status.fungi","effectCheckerFindDirectFlowCallsStatusCore","galerina-core-compiler/src/effect-checker.ts","findDirectFlowCalls","effect_checker_find_direct_flow_calls_built"],
  ["effect-checker-find-flow-node-status.fungi","effectCheckerFindFlowNodeStatusCore","galerina-core-compiler/src/effect-checker.ts","findFlowNode","effect_checker_find_flow_node_built"],
  ["effect-checker-has-transitive-effect-status.fungi","effectCheckerHasTransitiveEffectStatusCore","galerina-core-compiler/src/effect-checker.ts","hasTransitiveEffect","effect_checker_has_transitive_effect_built"],
  ["effect-checker-infer-direct-effects-for-flow-status.fungi","effectCheckerInferDirectEffectsForFlowStatusCore","galerina-core-compiler/src/effect-checker.ts","inferDirectEffectsForFlow","effect_checker_infer_direct_effects_for_flow_built"],
  ["effect-checker-infer-effect-call-locations-status.fungi","effectCheckerInferEffectCallLocationsStatusCore","galerina-core-compiler/src/effect-checker.ts","inferEffectCallLocations","effect_checker_infer_effect_call_locations_built"],
  ["effect-checker-infer-effects-for-call-text-status.fungi","effectCheckerInferEffectsForCallTextStatusCore","galerina-core-compiler/src/effect-checker.ts","inferEffectsForCallText","effect_checker_infer_effects_for_call_text_built"],
  ["effect-checker-infer-effects-for-operation-status.fungi","effectCheckerInferEffectsForOperationStatusCore","galerina-core-compiler/src/effect-checker.ts","inferEffectsForOperation","effect_checker_infer_effects_for_operation_built"],
  ["effect-checker-infer-effects-from-node-status.fungi","effectCheckerInferEffectsFromNodeStatusCore","galerina-core-compiler/src/effect-checker.ts","inferEffectsFromNode","effect_checker_infer_effects_from_node_built"],
  ["effect-checker-is-shadowed-stdlib-receiver-status.fungi","effectCheckerIsShadowedStdlibReceiverStatusCore","galerina-core-compiler/src/effect-checker.ts","isShadowedStdlibReceiver","effect_checker_is_shadowed_stdlib_receiver_built"],
  ["effect-checker-name-looks-like-module-status.fungi","effectCheckerNameLooksLikeModuleStatusCore","galerina-core-compiler/src/effect-checker.ts","nameLooksLikeModule","effect_checker_name_looks_like_module_built"],
  ["effect-checker-nearest-canonical-effect-status.fungi","effectCheckerNearestCanonicalEffectStatusCore","galerina-core-compiler/src/effect-checker.ts","nearestCanonicalEffect","effect_checker_nearest_canonical_effect_built"],
  ["effect-checker-receiver-looks-like-member-receiver-status.fungi","effectCheckerReceiverLooksLikeMemberReceiverStatusCore","galerina-core-compiler/src/effect-checker.ts","receiverLooksLikeMemberReceiver","effect_checker_receiver_looks_like_member_receiver_built"],
  ["effect-checker-root-receiver-raw-status.fungi","effectCheckerRootReceiverRawStatusCore","galerina-core-compiler/src/effect-checker.ts","rootReceiverRaw","effect_checker_root_receiver_raw_built"],
  ["effect-checker-validate-declared-effect-names-status.fungi","effectCheckerValidateDeclaredEffectNamesStatusCore","galerina-core-compiler/src/effect-checker.ts","validateDeclaredEffectNames","effect_checker_validate_declared_effect_names_built"],
  ["effect-checker-validate-inter-flow-propagation-status.fungi","effectCheckerValidateInterFlowPropagationStatusCore","galerina-core-compiler/src/effect-checker.ts","validateInterFlowPropagation","effect_checker_validate_inter_flow_propagation_built"],
  ["effect-checker-walk-status.fungi","effectCheckerWalkStatusCore","galerina-core-compiler/src/effect-checker.ts","function walk(n: AstNode): void","effect_checker_walk_built"],
  ["effect-checker-walk-for-effects-status.fungi","effectCheckerWalkForEffectsStatusCore","galerina-core-compiler/src/effect-checker.ts","walkForEffects","effect_checker_walk_for_effects_built"],
  ["effect-checker-walk-for-fns-status.fungi","effectCheckerWalkForFnsStatusCore","galerina-core-compiler/src/effect-checker.ts","walkForFns","effect_checker_walk_for_fns_built"],
  ["escape-analysis-is-record-literal-status.fungi","escapeAnalysisIsRecordLiteralStatusCore","galerina-core-compiler/src/escape-analysis.ts","isRecordLiteral","escape_analysis_is_record_literal_built"],
  ["escape-analysis-binding-name-status.fungi","escapeAnalysisBindingNameStatusCore","galerina-core-compiler/src/escape-analysis.ts","bindingName","escape_analysis_binding_name_built"],
  ["escape-analysis-collect-record-alloc-sites-status.fungi","escapeAnalysisCollectRecordAllocSitesStatusCore","galerina-core-compiler/src/escape-analysis.ts","collectRecordAllocSites","escape_analysis_collect_record_alloc_sites_built"],
  ["escape-analysis-compute-aliases-status.fungi","escapeAnalysisComputeAliasesStatusCore","galerina-core-compiler/src/escape-analysis.ts","computeAliases","escape_analysis_compute_aliases_built"],
  ["escape-analysis-collect-status.fungi","escapeAnalysisCollectStatusCore","galerina-core-compiler/src/escape-analysis.ts","const collect = (n: AstNode | undefined)","escape_analysis_collect_built"],
  ["escape-analysis-record-escapes-status.fungi","escapeAnalysisRecordEscapesStatusCore","galerina-core-compiler/src/escape-analysis.ts","recordEscapes","escape_analysis_record_escapes_built"],
].map(([file,flow,source,symbol,expected])=>Object.freeze({file,flow,source,symbol,input:args(["inputCaptured","stateChecked","decisionBuilt","evidenceBound","outcomeSealed"]),expected:string(expected)})));

function shadowFingerprint(source){const identifiers=new Map();return createHash("sha256").update(source.replace(/^\uFEFF/u," ").replace(/\/\*[\s\S]*?\*\//gu," ").replace(/^\s*\/\/.*$/gmu," ").replace(/\b((?:pure|secure)\s+)?flow\s+[A-Za-z_][A-Za-z0-9_]*/gu,m=>m.replace(/([A-Za-z_][A-Za-z0-9_]*)$/u,"FLOW")).replace(/"(?:\\.|[^"\\])*"/gu,'"STRING"').replace(/\b-?(?:0x[0-9a-fA-F_]+|\d[\d_]*)\b/gu,"NUMBER").replace(/\s+/gu," ").trim().replace(/\b[A-Za-z_][A-Za-z0-9_]*\b/gu,id=>{if(RESERVED.has(id))return id;let r=identifiers.get(id);if(r===undefined){r="ID"+identifiers.size;identifiers.set(id,r);}return r;}),"utf8").digest("hex");}

describe("40-file source-bound Fungi decision-core overlay wave 28",()=>{
  it("binds 40 distinct, previously uncredited live source behaviours and package assets",()=>{assert.equal(CANDIDATES.length,40);const loaded=JSON.parse(readFileSync(PACKAGE,"utf8")).packageGraph?.loadedAssets??[],scopes=new Set(),sources=new Map();for(const c of CANDIDATES){assert.ok(loaded.includes(`src/self-hosted/conversion-overlays/${c.file}`),`${c.file} must be a loaded asset`);let source=sources.get(c.source);if(source===undefined){source=readFileSync(join(ROOT,"packages-ts",c.source),"utf8");sources.set(c.source,source);}assert.ok(source.includes(c.symbol),`${c.source} must contain ${c.symbol}`);const scope=`${c.source}#${c.symbol}`;assert.equal(scopes.has(scope),false);scopes.add(scope);}});
  it("has no exact duplicate or normalized whole-corpus template shadow",()=>{const seen=new Map(),files=new Set(CANDIDATES.map(c=>c.file));for(const file of readdirSync(OVERLAY_ROOT).filter(f=>f.endsWith(".fungi")&&!files.has(f))){const source=readFileSync(join(OVERLAY_ROOT,file),"utf8");seen.set(createHash("sha256").update(source).digest("hex"),file);seen.set(shadowFingerprint(source),file);}const collisions=[];for(const c of CANDIDATES){const p=join(OVERLAY_ROOT,c.file);assert.ok(existsSync(p),`${c.file} must exist`);const source=readFileSync(p,"utf8");for(const [kind,fp] of [["exact duplicate",createHash("sha256").update(source).digest("hex")],["template shadow",shadowFingerprint(source)]]){if(seen.has(fp))collisions.push(`${c.file} ${kind} of ${seen.get(fp)}`);seen.set(fp,c.file);}}assert.deepEqual(collisions,[]);});
  it("parses, effect-checks, emits GIR and executes every decision core",async()=>{for(const c of CANDIDATES){const source=readFileSync(join(OVERLAY_ROOT,c.file),"utf8"),program=parseProgram(source,c.file);assert.deepEqual((program.diagnostics??[]).filter(d=>d.severity==="error"),[],c.file);const effects=checkEffects(program.flows,program.ast);assert.deepEqual(effects.flatMap(r=>r.diagnostics).filter(d=>d.severity==="error"),[],c.file);assert.equal(emitGIR(program.ast,program.flows,effects).gir.flows.length,1,c.file);assert.deepEqual((await executeFlow(c.flow,c.input,program.ast,program.flows)).value,c.expected,c.file);}});
});
