import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, it } from "node:test";
import { checkEffects, emitGIR, executeFlow, parseProgram } from "../../galerina-core-compiler/dist/index.js";

const ROOT=join(import.meta.dirname,"..","..",".."),PACKAGE_ROOT=join(ROOT,"packages-ts","galerina-test"),OVERLAY_ROOT=join(PACKAGE_ROOT,"src","self-hosted","conversion-overlays"),PACKAGE=join(PACKAGE_ROOT,"package.json");
const bool=value=>({__tag:"bool",value}),string=value=>({__tag:"string",value}),args=names=>new Map(names.map(name=>[name,bool(true)]));
const RESERVED=new Set(["version","pure","secure","flow","FLOW","contract","intent","record","return","if","match","check","deny","ambig","mut","let","Bool","Int","String","Verdict","Result","Option","Array","true","false","Ok","Err","Some","None","Allow","Deny","Unknown"]);
const CANDIDATES=Object.freeze([
  ["governance-verifier-describe-expr-status.fungi","governanceVerifierDescribeExprStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private describeExpr(","governance_verifier_describe_expr_built"],
  ["governance-verifier-verify-network-wildcard-ban-status.fungi","governanceVerifierVerifyNetworkWildcardBanStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private verifyNetworkWildcardBan(","governance_verifier_verify_network_wildcard_ban_built"],
  ["governance-verifier-verify-domain-guard-conformance-status.fungi","governanceVerifierVerifyDomainGuardConformanceStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private verifyDomainGuardConformance(","governance_verifier_verify_domain_guard_conformance_built"],
  ["governance-verifier-verify-tenant-isolation-status.fungi","governanceVerifierVerifyTenantIsolationStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private verifyTenantIsolation(","governance_verifier_verify_tenant_isolation_built"],
  ["governance-verifier-verify-vault-effects-status.fungi","governanceVerifierVerifyVaultEffectsStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private verifyVaultEffects(","governance_verifier_verify_vault_effects_built"],
  ["governance-verifier-verify-limits-block-status.fungi","governanceVerifierVerifyLimitsBlockStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private verifyLimitsBlock(","governance_verifier_verify_limits_block_built"],
  ["governance-verifier-verify-termination-annotation-status.fungi","governanceVerifierVerifyTerminationAnnotationStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private verifyTerminationAnnotation(","governance_verifier_verify_termination_annotation_built"],
  ["governance-verifier-verify-residency-hardening-block-status.fungi","governanceVerifierVerifyResidencyHardeningBlockStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private verifyResidencyHardeningBlock(","governance_verifier_verify_residency_hardening_block_built"],
  ["governance-verifier-flow-is-secret-shaped-status.fungi","governanceVerifierFlowIsSecretShapedStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private flowIsSecretShaped(","governance_verifier_flow_is_secret_shaped_built"],
  ["governance-verifier-has-secret-dependent-timing-status.fungi","governanceVerifierHasSecretDependentTimingStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private hasSecretDependentTiming(","governance_verifier_has_secret_dependent_timing_built"],
  ["governance-verifier-verify-physical-hardening-block-status.fungi","governanceVerifierVerifyPhysicalHardeningBlockStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private verifyPhysicalHardeningBlock(","governance_verifier_verify_physical_hardening_block_built"],
  ["governance-verifier-verify-liability-block-status.fungi","governanceVerifierVerifyLiabilityBlockStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private verifyLiabilityBlock(","governance_verifier_verify_liability_block_built"],
  ["governance-verifier-verify-policy-hierarchy-status.fungi","governanceVerifierVerifyPolicyHierarchyStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private verifyPolicyHierarchy(","governance_verifier_verify_policy_hierarchy_built"],
  ["governance-verifier-verify-policy-monotonicity-status.fungi","governanceVerifierVerifyPolicyMonotonicityStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private verifyPolicyMonotonicity(","governance_verifier_verify_policy_monotonicity_built"],
  ["governance-verifier-verify-epilogue-block-status.fungi","governanceVerifierVerifyEpilogueBlockStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private verifyEpilogueBlock(","governance_verifier_verify_epilogue_block_built"],
  ["governance-verifier-verify-trap-decls-status.fungi","governanceVerifierVerifyTrapDeclsStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private verifyTrapDecls(","governance_verifier_verify_trap_decls_built"],
  ["governance-verifier-verify-static-decls-status.fungi","governanceVerifierVerifyStaticDeclsStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private verifyStaticDecls(","governance_verifier_verify_static_decls_built"],
  ["governance-verifier-verify-bitfield-decls-status.fungi","governanceVerifierVerifyBitfieldDeclsStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private verifyBitfieldDecls(","governance_verifier_verify_bitfield_decls_built"],
  ["governance-verifier-verify-governed-flows-status.fungi","governanceVerifierVerifyGovernedFlowsStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private verifyGovernedFlows(","governance_verifier_verify_governed_flows_built"],
  ["governance-verifier-verify-assimilated-plugins-status.fungi","governanceVerifierVerifyAssimilatedPluginsStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private verifyAssimilatedPlugins(","governance_verifier_verify_assimilated_plugins_built"],
  ["governance-verifier-verify-gate-blocks-status.fungi","governanceVerifierVerifyGateBlocksStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private verifyGateBlocks(","governance_verifier_verify_gate_blocks_built"],
  ["governance-verifier-verify-access-blocks-status.fungi","governanceVerifierVerifyAccessBlocksStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private verifyAccessBlocks(","governance_verifier_verify_access_blocks_built"],
  ["governance-verifier-check-match-exhaustiveness-status.fungi","governanceVerifierCheckMatchExhaustivenessStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private checkMatchExhaustiveness(","governance_verifier_check_match_exhaustiveness_built"],
  ["governance-verifier-walk-for-match-expr-status.fungi","governanceVerifierWalkForMatchExprStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private walkForMatchExpr(","governance_verifier_walk_for_match_expr_built"],
  ["governance-verifier-verify-match-exhaustiveness-status.fungi","governanceVerifierVerifyMatchExhaustivenessStatusCore","galerina-core-compiler/src/governance-verifier.ts","  private verifyMatchExhaustiveness(","governance_verifier_verify_match_exhaustiveness_built"],
  ["governance-verifier-verify-governance-status.fungi","governanceVerifierVerifyGovernanceStatusCore","galerina-core-compiler/src/governance-verifier.ts","export function verifyGovernance(","governance_verifier_verify_governance_built"],
  ["gpu-plan-build-web-gpu-plan-status.fungi","gpuPlanBuildWebGpuPlanStatusCore","galerina-core-compiler/src/gpu-plan.ts","export function buildWebGPUPlan(","gpu_plan_build_web_gpu_plan_built"],
  ["gpu-plan-build-npu-plan-status.fungi","gpuPlanBuildNpuPlanStatusCore","galerina-core-compiler/src/gpu-plan.ts","export function buildNPUPlan(","gpu_plan_build_npu_plan_built"],
  ["gpu-plan-parse-shape-status.fungi","gpuPlanParseShapeStatusCore","galerina-core-compiler/src/gpu-plan.ts","function parseShape(","gpu_plan_parse_shape_built"],
  ["gpu-plan-build-apu-shared-memory-plan-status.fungi","gpuPlanBuildApuSharedMemoryPlanStatusCore","galerina-core-compiler/src/gpu-plan.ts","export function buildAPUSharedMemoryPlan(","gpu_plan_build_apu_shared_memory_plan_built"],
  ["hardening-residency-stricter-residency-status.fungi","hardeningResidencyStricterResidencyStatusCore","galerina-core-compiler/src/hardening-residency.ts","export function stricterResidency(","hardening_residency_stricter_residency_built"],
  ["hardening-residency-at-least-as-strict-status.fungi","hardeningResidencyAtLeastAsStrictStatusCore","galerina-core-compiler/src/hardening-residency.ts","export function atLeastAsStrict(","hardening_residency_at_least_as_strict_built"],
  ["hardening-residency-derive-auto-status.fungi","hardeningResidencyDeriveAutoStatusCore","galerina-core-compiler/src/hardening-residency.ts","export function deriveAuto(","hardening_residency_derive_auto_built"],
  ["hardening-residency-reconcile-explicit-status.fungi","hardeningResidencyReconcileExplicitStatusCore","galerina-core-compiler/src/hardening-residency.ts","export function reconcileExplicit(","hardening_residency_reconcile_explicit_built"],
  ["hardening-residency-pick-two-valued-status.fungi","hardeningResidencyPickTwoValuedStatusCore","galerina-core-compiler/src/hardening-residency.ts","function pickTwoValued<","hardening_residency_pick_two_valued_built"],
  ["hardening-residency-resolve-host-status.fungi","hardeningResidencyResolveHostStatusCore","galerina-core-compiler/src/hardening-residency.ts","export function resolveHost(","hardening_residency_resolve_host_built"],
  ["hardening-residency-can-honour-status.fungi","hardeningResidencyCanHonourStatusCore","galerina-core-compiler/src/hardening-residency.ts","export function canHonour(","hardening_residency_can_honour_built"],
  ["hardening-residency-trust-name-status.fungi","hardeningResidencyTrustNameStatusCore","galerina-core-compiler/src/hardening-residency.ts","export function trustName(","hardening_residency_trust_name_built"],
  ["hardening-residency-refute-status.fungi","hardeningResidencyRefuteStatusCore","galerina-core-compiler/src/hardening-residency.ts","export function refute(","hardening_residency_refute_built"],
  ["hardening-residency-combine-trust-status.fungi","hardeningResidencyCombineTrustStatusCore","galerina-core-compiler/src/hardening-residency.ts","export function combineTrust(","hardening_residency_combine_trust_built"],
].map(([file,flow,source,symbol,expected])=>Object.freeze({file,flow,source,symbol,input:args(["inputCaptured","stateChecked","decisionBuilt","evidenceBound","outcomeSealed","releaseChecked"]),expected:string(expected)})));

function shadowFingerprint(source){const identifiers=new Map();return createHash("sha256").update(source.replace(/^\uFEFF/u," ").replace(/\/\*[\s\S]*?\*\//gu," ").replace(/^\s*\/\/.*$/gmu," ").replace(/\b((?:pure|secure)\s+)?flow\s+[A-Za-z_][A-Za-z0-9_]*/gu,m=>m.replace(/([A-Za-z_][A-Za-z0-9_]*)$/u,"FLOW")).replace(/"(?:\\.|[^"\\])*"/gu,'"STRING"').replace(/\b-?(?:0x[0-9a-fA-F_]+|\d[\d_]*)\b/gu,"NUMBER").replace(/\s+/gu," ").trim().replace(/\b[A-Za-z_][A-Za-z0-9_]*\b/gu,id=>{if(RESERVED.has(id))return id;let r=identifiers.get(id);if(r===undefined){r="ID"+identifiers.size;identifiers.set(id,r);}return r;}),"utf8").digest("hex");}

describe("40-file source-bound Fungi decision-core overlay wave 35",()=>{
  it("binds 40 distinct, previously uncredited live source behaviours and package assets",()=>{assert.equal(CANDIDATES.length,40);const loaded=JSON.parse(readFileSync(PACKAGE,"utf8")).packageGraph?.loadedAssets??[],scopes=new Set();for(const c of CANDIDATES){assert.ok(loaded.includes(`src/self-hosted/conversion-overlays/${c.file}`),`${c.file} must be a loaded asset`);const source=readFileSync(join(ROOT,"packages-ts",c.source),"utf8");assert.ok(source.includes(c.symbol),`${c.source} must contain ${c.symbol}`);const scope=`${c.source}#${c.symbol}`;assert.equal(scopes.has(scope),false);scopes.add(scope);}});
  it("has no exact duplicate or normalized whole-corpus template shadow",()=>{const seen=new Map(),files=new Set(CANDIDATES.map(c=>c.file));for(const file of readdirSync(OVERLAY_ROOT).filter(f=>f.endsWith(".fungi")&&!files.has(f))){const source=readFileSync(join(OVERLAY_ROOT,file),"utf8");seen.set(createHash("sha256").update(source).digest("hex"),file);seen.set(shadowFingerprint(source),file);}const collisions=[];for(const c of CANDIDATES){const p=join(OVERLAY_ROOT,c.file);assert.ok(existsSync(p),`${c.file} must exist`);const source=readFileSync(p,"utf8");for(const [kind,fp] of [["exact duplicate",createHash("sha256").update(source).digest("hex")],["template shadow",shadowFingerprint(source)]]){if(seen.has(fp))collisions.push(`${c.file} ${kind} of ${seen.get(fp)}`);seen.set(fp,c.file);}}assert.deepEqual(collisions,[]);});
  it("parses, effect-checks, emits GIR and executes every decision core",async()=>{for(const c of CANDIDATES){const source=readFileSync(join(OVERLAY_ROOT,c.file),"utf8"),program=parseProgram(source,c.file);assert.deepEqual((program.diagnostics??[]).filter(d=>d.severity==="error"),[],c.file);const effects=checkEffects(program.flows,program.ast);assert.deepEqual(effects.flatMap(r=>r.diagnostics).filter(d=>d.severity==="error"),[],c.file);assert.equal(emitGIR(program.ast,program.flows,effects).gir.flows.length,1,c.file);assert.deepEqual((await executeFlow(c.flow,c.input,program.ast,program.flows)).value,c.expected,c.file);}});
});
