import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { it } from "node:test";

const SLIDE_ROOT=process.env.GALERINA_SLIDE_REPO,AVAILABLE=typeof SLIDE_ROOT==="string"&&existsSync(join(SLIDE_ROOT,"src","checked-fungi-package-compiler.mjs")),ROOT=join(process.cwd(),"packages-galerina","galerina-test","src","self-hosted","conversion-overlays"),GATES=Object.freeze({identity:1,provenance:1,target:1,effects:1,policy:1,revocation:1,validation:1,memory:1});
const STEMS=Object.freeze(["proof-graph-diff-fingerprints","pure-flow-cache-max-entries","pure-flow-cache-lru-node","pure-flow-cache-lru-cache","pure-flow-cache-lru-cache-constructor","pure-flow-cache-lru-cache-get","pure-flow-cache-lru-cache-set","pure-flow-cache-lru-cache-clear","pure-flow-cache-lru-cache-stats","pure-flow-cache-lru-cache-move-to-front","pure-flow-cache-lru-cache-add-to-front","pure-flow-cache-lru-cache-remove-node","pure-flow-cache-lru-cache-evict-last","pure-flow-cache-session-cache","pure-flow-cache-fnv-prime","pure-flow-cache-fnv-offset","pure-flow-cache-fnv-byte","pure-flow-cache-fnv-int","pure-flow-cache-fnv-str","pure-flow-cache-galerina-value-fingerprint","pure-flow-cache-pure-flow-cache-key","pure-flow-cache-get-cached-pure-flow","pure-flow-cache-set-cached-pure-flow","pure-flow-cache-clear-pure-flow-cache","pure-flow-cache-get-pure-flow-cache-stats","register-vm-register-id","register-vm-constant-pool-index","register-vm-register-opcode","register-vm-register-instruction","register-vm-register-function","register-vm-register-bytecode-module","register-vm-emit-bytecode","resilience-inference-resilience-fallback","resilience-inference-backoff-strategy","resilience-inference-fault-signal","resilience-inference-fault-action","resilience-inference-fault-handler","resilience-inference-inferred-resilience","resilience-inference-mutation-effects","resilience-inference-network-effects"]);
const camel=s=>s.split("-").map((p,i)=>i?p[0].toUpperCase()+p.slice(1):p).join(""),CANDIDATES=Object.freeze(STEMS.map(stem=>Object.freeze({file:`${stem}-status.fungi`,flow:`${camel(stem)}StatusCore`,args:Array(7).fill(true),expected:`${stem.replaceAll("-","_")}_built`}))),TEST_CANDIDATES=Object.freeze(CANDIDATES.slice(0,10));
async function api(){const load=async p=>import(pathToFileURL(join(SLIDE_ROOT,"src",p)).href);return {...await load("checked-fungi-package-compiler.mjs"),...await load("checked-fungi-package-file.mjs"),...await load("checked-fungi-package-publication-loader.mjs"),...await load("safe-value-envelope.mjs"),...await load("portable-veo.mjs")};}
function expectation(r){return {packageSetDigest:r.packageSetDigest,packageIdentity:r.packageIdentity,exportName:r.exportName,receiptDigest:r.receiptDigest,safeValueTypeId:r.safeValueTypeId,safeValueStateId:r.safeValueStateId,safeValueProvenanceDigest:r.safeValueProvenanceDigest};}
it("publishes and independently re-admits a deterministic 10-file wave-49 sample through physical SLIDE/VOK",{skip:!AVAILABLE},async()=>{const slide=await api(),context=slide.portableVeoReferenceContext(),sources=TEST_CANDIDATES.map(c=>Uint8Array.from(readFileSync(join(ROOT,c.file)))),request=bytes=>({packages:[{identity:"@galerina/test",version:"1.0.0-beta.49",exports:TEST_CANDIDATES.map((c,i)=>({name:c.flow,sourceFlowName:c.flow,sourceBytes:bytes[i]})),dependencies:[],resources:[]}],context,gates:GATES}),compiled=slide.compileCheckedFungiPackageSet(request(sources));assert.equal(compiled.verdict,1,JSON.stringify(compiled));const changed=sources.map(source=>Uint8Array.from(source));changed[0][0]^=1;assert.equal(slide.compileCheckedFungiPackageSet(request(changed)).verdict,-1);const parent=await mkdtemp(join(tmpdir(),"galerina-wave-49-")),out=join(parent,"published");try{const published=await slide.publishCheckedFungiPackageBuild({packageBuildHandle:compiled.packageBuildHandle,outputDirectory:out});assert.equal(published.verdict,1,JSON.stringify(published));assert.equal(published.outputFiles.filter(n=>n.endsWith(".slide")).length,10);let last;for(const c of TEST_CANDIDATES){const prepared=await slide.prepareCheckedFungiPackagePublication({publicationDirectory:out,packageIdentity:"@galerina/test",exportName:c.flow,context,gates:GATES});assert.equal(prepared.verdict,1,c.flow);const receipt=slide.executeTypedCheckedFungiPackagePublication(prepared.packageExecutionHandle,c.args,undefined),verified=slide.verifyTypedCheckedFungiPackageReceipt(receipt,expectation(receipt));assert.equal(verified.verdict,1,c.flow);assert.equal(verified.value,c.expected,c.flow);assert.equal(verified.authorityReleased,false,c.flow);last=receipt;}assert.equal(slide.verifyTypedCheckedFungiPackageReceipt({...last,receiptDigest:"sha256:"+"0".repeat(64)},expectation(last)).verdict,-1);const path=join(out,published.outputFiles.find(n=>n.endsWith(".slide"))),bytes=await readFile(path);bytes[0]^=1;await writeFile(path,bytes);assert.equal((await slide.prepareCheckedFungiPackagePublication({publicationDirectory:out,packageIdentity:"@galerina/test",exportName:TEST_CANDIDATES[0].flow,context,gates:GATES})).verdict,-1);}finally{await rm(parent,{recursive:true,force:true});}});
