import assert from "node:assert/strict";import { existsSync, readFileSync } from "node:fs";import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";import { tmpdir } from "node:os";import { join } from "node:path";import { pathToFileURL } from "node:url";import { it } from "node:test";
const SLIDE_ROOT=process.env.GALERINA_SLIDE_REPO,AVAILABLE=typeof SLIDE_ROOT==="string"&&existsSync(join(SLIDE_ROOT,"src","checked-fungi-package-compiler.mjs")),ROOT=join(process.cwd(),"packages-galerina","galerina-test","src","self-hosted","conversion-overlays"),GATES=Object.freeze({identity:1,provenance:1,target:1,effects:1,policy:1,revocation:1,validation:1,memory:1});
const CANDIDATES=Object.freeze([
  ["value-state-is-governed-sink-status.fungi","valueStateIsGovernedSinkStatusCore",3,"value_state_is_governed_sink_built"],
  ["value-state-is-model-sink-status.fungi","valueStateIsModelSinkStatusCore",3,"value_state_is_model_sink_built"],
  ["value-state-is-network-sink-status.fungi","valueStateIsNetworkSinkStatusCore",3,"value_state_is_network_sink_built"],
  ["value-state-is-protected-value-expression-status.fungi","valueStateIsProtectedValueExpressionStatusCore",3,"value_state_is_protected_value_expression_built"],
  ["value-state-is-redact-call-status.fungi","valueStateIsRedactCallStatusCore",3,"value_state_is_redact_call_built"],
  ["value-state-is-seal-call-status.fungi","valueStateIsSealCallStatusCore",3,"value_state_is_seal_call_built"],
  ["value-state-is-tainted-expression-status.fungi","valueStateIsTaintedExpressionStatusCore",3,"value_state_is_tainted_expression_built"],
  ["value-state-is-untrusted-source-from-origin-status.fungi","valueStateIsUntrustedSourceFromOriginStatusCore",3,"value_state_is_untrusted_source_from_origin_built"],
  ["value-state-lookup-binding-status.fungi","valueStateLookupBindingStatusCore",3,"value_state_lookup_binding_built"],
  ["value-state-make-vs-diag-status.fungi","valueStateMakeVsDiagStatusCore",3,"value_state_make_vs_diag_built"],
  ["value-state-parse-binding-value-status.fungi","valueStateParseBindingValueStatusCore",3,"value_state_parse_binding_value_built"],
  ["value-state-pop-scope-status.fungi","valueStatePopScopeStatusCore",3,"value_state_pop_scope_built"],
  ["value-state-push-scope-status.fungi","valueStatePushScopeStatusCore",3,"value_state_push_scope_built"],
  ["value-state-receiver-segment-status.fungi","valueStateReceiverSegmentStatusCore",3,"value_state_receiver_segment_built"],
  ["value-state-register-binding-status.fungi","valueStateRegisterBindingStatusCore",3,"value_state_register_binding_built"],
  ["value-state-register-param-binding-status.fungi","valueStateRegisterParamBindingStatusCore",3,"value_state_register_param_binding_built"],
  ["value-state-required-passport-stage-status.fungi","valueStateRequiredPassportStageStatusCore",3,"value_state_required_passport_stage_built"],
  ["value-state-scan-declassifier-shadows-status.fungi","valueStateScanDeclassifierShadowsStatusCore",3,"value_state_scan_declassifier_shadows_built"],
  ["value-state-scan-unlowerable-numerics-status.fungi","valueStateScanUnlowerableNumericsStatusCore",3,"value_state_scan_unlowerable_numerics_built"],
  ["value-state-unlowerable-numeric-diag-status.fungi","valueStateUnlowerableNumericDiagStatusCore",3,"value_state_unlowerable_numeric_diag_built"],
  ["value-state-update-binding-status.fungi","valueStateUpdateBindingStatusCore",3,"value_state_update_binding_built"],
  ["value-state-walk-children-status.fungi","valueStateWalkChildrenStatusCore",3,"value_state_walk_children_built"],
  ["value-state-walk-node-status.fungi","valueStateWalkNodeStatusCore",3,"value_state_walk_node_built"],
  ["type-checker-is-built-in-type-status.fungi","typeCheckerIsBuiltInTypeStatusCore",3,"type_checker_is_built_in_type_built"],
  ["type-checker-make-tc-diag-status.fungi","typeCheckerMakeTcDiagStatusCore",3,"type_checker_make_tc_diag_built"],
  ["type-checker-governance-qualifier-status.fungi","typeCheckerGovernanceQualifierStatusCore",3,"type_checker_governance_qualifier_built"],
  ["type-checker-parse-type-string-status.fungi","typeCheckerParseTypeStringStatusCore",3,"type_checker_parse_type_string_built"],
  ["type-checker-is-assignment-compatible-status.fungi","typeCheckerIsAssignmentCompatibleStatusCore",3,"type_checker_is_assignment_compatible_built"],
  ["type-checker-try-record-literal-adoption-status.fungi","typeCheckerTryRecordLiteralAdoptionStatusCore",3,"type_checker_try_record_literal_adoption_built"],
  ["type-checker-check-duplicate-top-level-types-status.fungi","typeCheckerCheckDuplicateTopLevelTypesStatusCore",3,"type_checker_check_duplicate_top_level_types_built"],
  ["type-checker-check-duplicate-top-level-governance-status.fungi","typeCheckerCheckDuplicateTopLevelGovernanceStatusCore",3,"type_checker_check_duplicate_top_level_governance_built"],
  ["type-checker-get-result-status.fungi","typeCheckerGetResultStatusCore",3,"type_checker_get_result_built"],
  ["type-checker-collect-declarations-status.fungi","typeCheckerCollectDeclarationsStatusCore",3,"type_checker_collect_declarations_built"],
  ["type-checker-push-binding-scope-status.fungi","typeCheckerPushBindingScopeStatusCore",3,"type_checker_push_binding_scope_built"],
  ["type-checker-pop-binding-scope-status.fungi","typeCheckerPopBindingScopeStatusCore",3,"type_checker_pop_binding_scope_built"],
  ["type-checker-lookup-binding-in-current-scope-status.fungi","typeCheckerLookupBindingInCurrentScopeStatusCore",3,"type_checker_lookup_binding_in_current_scope_built"],
  ["type-checker-register-binding-kind-status.fungi","typeCheckerRegisterBindingKindStatusCore",3,"type_checker_register_binding_kind_built"],
  ["type-checker-lookup-binding-kind-status.fungi","typeCheckerLookupBindingKindStatusCore",3,"type_checker_lookup_binding_kind_built"],
  ["type-checker-reserved-hallmark-message-status.fungi","typeCheckerReservedHallmarkMessageStatusCore",3,"type_checker_reserved_hallmark_message_built"],
  ["type-checker-check-hallmark-decl-status.fungi","typeCheckerCheckHallmarkDeclStatusCore",3,"type_checker_check_hallmark_decl_built"],
].map(([file,flow,count,expected])=>Object.freeze({file,flow,args:Array(count).fill(true),expected})));
async function api(){const load=async p=>import(pathToFileURL(join(SLIDE_ROOT,"src",p)).href);return {...await load("checked-fungi-package-compiler.mjs"),...await load("checked-fungi-package-file.mjs"),...await load("checked-fungi-package-publication-loader.mjs"),...await load("safe-value-envelope.mjs"),...await load("portable-veo.mjs")};}function expectation(r){return {packageSetDigest:r.packageSetDigest,packageIdentity:r.packageIdentity,exportName:r.exportName,receiptDigest:r.receiptDigest,safeValueTypeId:r.safeValueTypeId,safeValueStateId:r.safeValueStateId,safeValueProvenanceDigest:r.safeValueProvenanceDigest};}
it("publishes and independently re-admits all 40 wave-26 source decisions through physical SLIDE/VOK",{skip:!AVAILABLE},async()=>{const slide=await api(),context=slide.portableVeoReferenceContext(),sources=CANDIDATES.map(c=>Uint8Array.from(readFileSync(join(ROOT,c.file)))),request=bytes=>({packages:[{identity:"@galerina/test",version:"1.0.0-beta.26",exports:CANDIDATES.map((c,i)=>({name:c.flow,sourceFlowName:c.flow,sourceBytes:bytes[i]})),dependencies:[],resources:[]}],context,gates:GATES}),compiled=slide.compileCheckedFungiPackageSet(request(sources));assert.equal(compiled.verdict,1,JSON.stringify(compiled));const changed=sources.map(source=>Uint8Array.from(source));changed[0][0]^=1;assert.equal(slide.compileCheckedFungiPackageSet(request(changed)).verdict,-1);const parent=await mkdtemp(join(tmpdir(),"galerina-wave-26-")),out=join(parent,"published");try{const published=await slide.publishCheckedFungiPackageBuild({packageBuildHandle:compiled.packageBuildHandle,outputDirectory:out});assert.equal(published.verdict,1,JSON.stringify(published));assert.equal(published.outputFiles.filter(n=>n.endsWith(".slide")).length,40);let last;for(const c of CANDIDATES){const prepared=await slide.prepareCheckedFungiPackagePublication({publicationDirectory:out,packageIdentity:"@galerina/test",exportName:c.flow,context,gates:GATES});assert.equal(prepared.verdict,1,c.flow);const receipt=slide.executeTypedCheckedFungiPackagePublication(prepared.packageExecutionHandle,c.args,undefined),verified=slide.verifyTypedCheckedFungiPackageReceipt(receipt,expectation(receipt));assert.equal(verified.verdict,1,c.flow);assert.equal(verified.value,c.expected,c.flow);assert.equal(verified.authorityReleased,false,c.flow);last=receipt;}assert.equal(slide.verifyTypedCheckedFungiPackageReceipt({...last,receiptDigest:"sha256:"+"0".repeat(64)},expectation(last)).verdict,-1);const path=join(out,published.outputFiles.find(n=>n.endsWith(".slide")));const bytes=await readFile(path);bytes[0]^=1;await writeFile(path,bytes);assert.equal((await slide.prepareCheckedFungiPackagePublication({publicationDirectory:out,packageIdentity:"@galerina/test",exportName:CANDIDATES[0].flow,context,gates:GATES})).verdict,-1);}finally{await rm(parent,{recursive:true,force:true});}});
