import assert from "node:assert/strict";import { existsSync, readFileSync } from "node:fs";import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";import { tmpdir } from "node:os";import { join } from "node:path";import { pathToFileURL } from "node:url";import { it } from "node:test";
const SLIDE_ROOT=process.env.GALERINA_SLIDE_REPO,AVAILABLE=typeof SLIDE_ROOT==="string"&&existsSync(join(SLIDE_ROOT,"src","checked-fungi-package-compiler.mjs")),ROOT=join(process.cwd(),"packages-ts","galerina-test","src","self-hosted","conversion-overlays"),GATES=Object.freeze({identity:1,provenance:1,target:1,effects:1,policy:1,revocation:1,validation:1,memory:1});
const CANDIDATES=Object.freeze([
  ["escape-analysis-assert-flow-local-status.fungi","escapeAnalysisAssertFlowLocalStatusCore",6,"escape_analysis_assert_flow_local_built"],
  ["escape-analysis-collect-record-field-types-status.fungi","escapeAnalysisCollectRecordFieldTypesStatusCore",6,"escape_analysis_collect_record_field_types_built"],
  ["escape-analysis-collect-record-literals-status.fungi","escapeAnalysisCollectRecordLiteralsStatusCore",6,"escape_analysis_collect_record_literals_built"],
  ["escape-analysis-window-is-arena-safe-status.fungi","escapeAnalysisWindowIsArenaSafeStatusCore",6,"escape_analysis_window_is_arena_safe_built"],
  ["event-checker-collect-contract-emits-status.fungi","eventCheckerCollectContractEmitsStatusCore",6,"event_checker_collect_contract_emits_built"],
  ["event-checker-collect-body-emits-status.fungi","eventCheckerCollectBodyEmitsStatusCore",6,"event_checker_collect_body_emits_built"],
  ["event-checker-walk-body-status.fungi","eventCheckerWalkBodyStatusCore",6,"event_checker_walk_body_built"],
  ["event-checker-check-events-status.fungi","eventCheckerCheckEventsStatusCore",6,"event_checker_check_events_built"],
  ["event-checker-walk-status.fungi","eventCheckerWalkStatusCore",6,"event_checker_walk_built"],
  ["execution-graph-weigh-graph-status.fungi","executionGraphWeighGraphStatusCore",6,"execution_graph_weigh_graph_built"],
  ["execution-graph-walk-status.fungi","executionGraphWalkStatusCore",6,"execution_graph_walk_built"],
  ["execution-graph-get-cached-graph-status.fungi","executionGraphGetCachedGraphStatusCore",6,"execution_graph_get_cached_graph_built"],
  ["execution-graph-get-or-load-graph-status.fungi","executionGraphGetOrLoadGraphStatusCore",6,"execution_graph_get_or_load_graph_built"],
  ["execution-graph-store-graph-status.fungi","executionGraphStoreGraphStatusCore",6,"execution_graph_store_graph_built"],
  ["execution-graph-reset-graph-cache-for-test-status.fungi","executionGraphResetGraphCacheForTestStatusCore",6,"execution_graph_reset_graph_cache_for_test_built"],
  ["execution-graph-build-execution-graph-status.fungi","executionGraphBuildExecutionGraphStatusCore",6,"execution_graph_build_execution_graph_built"],
  ["execution-graph-alloc-slot-status.fungi","executionGraphAllocSlotStatusCore",6,"execution_graph_alloc_slot_built"],
  ["execution-graph-add-const-status.fungi","executionGraphAddConstStatusCore",6,"execution_graph_add_const_built"],
  ["execution-graph-emit-status.fungi","executionGraphEmitStatusCore",6,"execution_graph_emit_built"],
  ["execution-graph-walk-node-status.fungi","executionGraphWalkNodeStatusCore",6,"execution_graph_walk_node_built"],
  ["execution-graph-cache-key-status.fungi","executionGraphCacheKeyStatusCore",6,"execution_graph_cache_key_built"],
  ["execution-graph-graph-was-known-status.fungi","executionGraphGraphWasKnownStatusCore",6,"execution_graph_graph_was_known_built"],
  ["execution-graph-get-graph-cache-stats-status.fungi","executionGraphGetGraphCacheStatsStatusCore",6,"execution_graph_get_graph_cache_stats_built"],
  ["fix-edit-overlaps-status.fungi","fixEditOverlapsStatusCore",6,"fix_edit_overlaps_built"],
  ["fix-edit-apply-fix-edits-status.fungi","fixEditApplyFixEditsStatusCore",6,"fix_edit_apply_fix_edits_built"],
  ["fix-edit-compute-auto-fix-status.fungi","fixEditComputeAutoFixStatusCore",6,"fix_edit_compute_auto_fix_built"],
  ["flat-token-stream-kind-status.fungi","flatTokenStreamKindStatusCore",6,"flat_token_stream_kind_built"],
  ["flat-token-stream-start-status.fungi","flatTokenStreamStartStatusCore",6,"flat_token_stream_start_built"],
  ["flat-token-stream-end-status.fungi","flatTokenStreamEndStatusCore",6,"flat_token_stream_end_built"],
  ["flat-token-stream-value-status.fungi","flatTokenStreamValueStatusCore",6,"flat_token_stream_value_built"],
  ["flat-token-stream-to-flat-token-stream-status.fungi","flatTokenStreamToFlatTokenStreamStatusCore",6,"flat_token_stream_to_flat_token_stream_built"],
  ["flow-complexity-cyclomatic-complexity-status.fungi","flowComplexityCyclomaticComplexityStatusCore",6,"flow_complexity_cyclomatic_complexity_built"],
  ["flow-complexity-walk-status.fungi","flowComplexityWalkStatusCore",6,"flow_complexity_walk_built"],
  ["flow-complexity-render-complexity-comment-status.fungi","flowComplexityRenderComplexityCommentStatusCore",6,"flow_complexity_render_complexity_comment_built"],
  ["flow-dependency-analyze-flow-dependencies-status.fungi","flowDependencyAnalyzeFlowDependenciesStatusCore",6,"flow_dependency_analyze_flow_dependencies_built"],
  ["flow-dependency-analyze-program-flow-dependencies-status.fungi","flowDependencyAnalyzeProgramFlowDependenciesStatusCore",6,"flow_dependency_analyze_program_flow_dependencies_built"],
  ["flow-dependency-render-dependency-comments-status.fungi","flowDependencyRenderDependencyCommentsStatusCore",6,"flow_dependency_render_dependency_comments_built"],
  ["flow-dependency-rewrite-generated-comments-status.fungi","flowDependencyRewriteGeneratedCommentsStatusCore",6,"flow_dependency_rewrite_generated_comments_built"],
  ["flow-name-decode-flow-decl-status.fungi","flowNameDecodeFlowDeclStatusCore",6,"flow_name_decode_flow_decl_built"],
  ["flow-name-is-flow-decl-named-status.fungi","flowNameIsFlowDeclNamedStatusCore",6,"flow_name_is_flow_decl_named_built"],
].map(([file,flow,count,expected])=>Object.freeze({file,flow,args:Array(count).fill(true),expected})));
async function api(){const load=async p=>import(pathToFileURL(join(SLIDE_ROOT,"src",p)).href);return {...await load("checked-fungi-package-compiler.mjs"),...await load("checked-fungi-package-file.mjs"),...await load("checked-fungi-package-publication-loader.mjs"),...await load("safe-value-envelope.mjs"),...await load("portable-veo.mjs")};}function expectation(r){return {packageSetDigest:r.packageSetDigest,packageIdentity:r.packageIdentity,exportName:r.exportName,receiptDigest:r.receiptDigest,safeValueTypeId:r.safeValueTypeId,safeValueStateId:r.safeValueStateId,safeValueProvenanceDigest:r.safeValueProvenanceDigest};}
it("publishes and independently re-admits all 40 wave-29 source decisions through physical SLIDE/VOK",{skip:!AVAILABLE},async()=>{const slide=await api(),context=slide.portableVeoReferenceContext(),sources=CANDIDATES.map(c=>Uint8Array.from(readFileSync(join(ROOT,c.file)))),request=bytes=>({packages:[{identity:"@galerina/test",version:"1.0.0-beta.29",exports:CANDIDATES.map((c,i)=>({name:c.flow,sourceFlowName:c.flow,sourceBytes:bytes[i]})),dependencies:[],resources:[]}],context,gates:GATES}),compiled=slide.compileCheckedFungiPackageSet(request(sources));assert.equal(compiled.verdict,1,JSON.stringify(compiled));const changed=sources.map(source=>Uint8Array.from(source));changed[0][0]^=1;assert.equal(slide.compileCheckedFungiPackageSet(request(changed)).verdict,-1);const parent=await mkdtemp(join(tmpdir(),"galerina-wave-29-")),out=join(parent,"published");try{const published=await slide.publishCheckedFungiPackageBuild({packageBuildHandle:compiled.packageBuildHandle,outputDirectory:out});assert.equal(published.verdict,1,JSON.stringify(published));assert.equal(published.outputFiles.filter(n=>n.endsWith(".slide")).length,40);let last;for(const c of CANDIDATES){const prepared=await slide.prepareCheckedFungiPackagePublication({publicationDirectory:out,packageIdentity:"@galerina/test",exportName:c.flow,context,gates:GATES});assert.equal(prepared.verdict,1,c.flow);const receipt=slide.executeTypedCheckedFungiPackagePublication(prepared.packageExecutionHandle,c.args,undefined),verified=slide.verifyTypedCheckedFungiPackageReceipt(receipt,expectation(receipt));assert.equal(verified.verdict,1,c.flow);assert.equal(verified.value,c.expected,c.flow);assert.equal(verified.authorityReleased,false,c.flow);last=receipt;}assert.equal(slide.verifyTypedCheckedFungiPackageReceipt({...last,receiptDigest:"sha256:"+"0".repeat(64)},expectation(last)).verdict,-1);const path=join(out,published.outputFiles.find(n=>n.endsWith(".slide")));const bytes=await readFile(path);bytes[0]^=1;await writeFile(path,bytes);assert.equal((await slide.prepareCheckedFungiPackagePublication({publicationDirectory:out,packageIdentity:"@galerina/test",exportName:CANDIDATES[0].flow,context,gates:GATES})).verdict,-1);}finally{await rm(parent,{recursive:true,force:true});}});
