import assert from "node:assert/strict";import { existsSync, readFileSync } from "node:fs";import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";import { tmpdir } from "node:os";import { join } from "node:path";import { pathToFileURL } from "node:url";import { it } from "node:test";
const SLIDE_ROOT=process.env.GALERINA_SLIDE_REPO,AVAILABLE=typeof SLIDE_ROOT==="string"&&existsSync(join(SLIDE_ROOT,"src","checked-fungi-package-compiler.mjs")),ROOT=join(process.cwd(),"packages-galerina","galerina-test","src","self-hosted","conversion-overlays"),GATES=Object.freeze({identity:1,provenance:1,target:1,effects:1,policy:1,revocation:1,validation:1,memory:1});
const CANDIDATES=Object.freeze([
  ["fused-pass-pack-opcode-status.fungi","fusedPassPackOpcodeStatusCore",6,"fused_pass_pack_opcode_built"],
  ["fused-pass-unpack-op-status.fungi","fusedPassUnpackOpStatusCore",6,"fused_pass_unpack_op_built"],
  ["fused-pass-unpack-type-id-status.fungi","fusedPassUnpackTypeIdStatusCore",6,"fused_pass_unpack_type_id_built"],
  ["fused-pass-unpack-effect-mask-status.fungi","fusedPassUnpackEffectMaskStatusCore",6,"fused_pass_unpack_effect_mask_built"],
  ["fused-pass-unpack-flags-status.fungi","fusedPassUnpackFlagsStatusCore",6,"fused_pass_unpack_flags_built"],
  ["fused-pass-fused-compile-status.fungi","fusedPassFusedCompileStatusCore",6,"fused_pass_fused_compile_built"],
  ["fused-pass-emit-status.fungi","fusedPassEmitStatusCore",6,"fused_pass_emit_built"],
  ["fused-pass-error-status.fungi","fusedPassErrorStatusCore",6,"fused_pass_error_built"],
  ["fused-pass-skip-ws-status.fungi","fusedPassSkipWsStatusCore",6,"fused_pass_skip_ws_built"],
  ["fused-pass-match-keyword-status.fungi","fusedPassMatchKeywordStatusCore",6,"fused_pass_match_keyword_built"],
  ["fused-pass-read-identifier-status.fungi","fusedPassReadIdentifierStatusCore",6,"fused_pass_read_identifier_built"],
  ["gate-dispatch-dispatch-gate-source-status.fungi","gateDispatchDispatchGateSourceStatusCore",6,"gate_dispatch_dispatch_gate_source_built"],
  ["gate-dispatch-find-gate-registry-status.fungi","gateDispatchFindGateRegistryStatusCore",6,"gate_dispatch_find_gate_registry_built"],
  ["gate-from-pattern-refuse-status.fungi","gateFromPatternRefuseStatusCore",6,"gate_from_pattern_refuse_built"],
  ["gate-from-pattern-parse-alternation-status.fungi","gateFromPatternParseAlternationStatusCore",6,"gate_from_pattern_parse_alternation_built"],
  ["gate-from-pattern-parse-sequence-status.fungi","gateFromPatternParseSequenceStatusCore",6,"gate_from_pattern_parse_sequence_built"],
  ["gate-from-pattern-parse-atom-status.fungi","gateFromPatternParseAtomStatusCore",6,"gate_from_pattern_parse_atom_built"],
  ["gate-from-pattern-parse-quantifier-status.fungi","gateFromPatternParseQuantifierStatusCore",6,"gate_from_pattern_parse_quantifier_built"],
  ["gate-from-pattern-count-parts-status.fungi","gateFromPatternCountPartsStatusCore",6,"gate_from_pattern_count_parts_built"],
  ["gate-from-pattern-emit-status.fungi","gateFromPatternEmitStatusCore",6,"gate_from_pattern_emit_built"],
  ["gate-from-pattern-generate-circuit-from-pattern-status.fungi","gateFromPatternGenerateCircuitFromPatternStatusCore",6,"gate_from_pattern_generate_circuit_from_pattern_built"],
  ["gate-parser-strip-inline-comment-status.fungi","gateParserStripInlineCommentStatusCore",6,"gate_parser_strip_inline_comment_built"],
  ["gate-parser-parse-gate-header-status.fungi","gateParserParseGateHeaderStatusCore",6,"gate_parser_parse_gate_header_built"],
  ["gate-parser-parse-gate-node-status.fungi","gateParserParseGateNodeStatusCore",6,"gate_parser_parse_gate_node_built"],
  ["gate-parser-parse-gate-edge-status.fungi","gateParserParseGateEdgeStatusCore",6,"gate_parser_parse_gate_edge_built"],
  ["gate-parser-parse-gate-flow-status.fungi","gateParserParseGateFlowStatusCore",6,"gate_parser_parse_gate_flow_built"],
  ["gate-parser-dedup-status.fungi","gateParserDedupStatusCore",6,"gate_parser_dedup_built"],
  ["gate-parser-gate-flow-name-status.fungi","gateParserGateFlowNameStatusCore",6,"gate_parser_gate_flow_name_built"],
  ["gate-parser-lower-gate-status.fungi","gateParserLowerGateStatusCore",6,"gate_parser_lower_gate_built"],
  ["gate-parser-parse-gate-status.fungi","gateParserParseGateStatusCore",6,"gate_parser_parse_gate_built"],
  ["gate-v3-admission-sha256-status.fungi","gateV3AdmissionSha256StatusCore",6,"gate_v3_admission_sha256_built"],
  ["gate-v3-admission-verify-admission-bindings-status.fungi","gateV3AdmissionVerifyAdmissionBindingsStatusCore",6,"gate_v3_admission_verify_admission_bindings_built"],
  ["gate-v3-admission-build-admission-statement-status.fungi","gateV3AdmissionBuildAdmissionStatementStatusCore",6,"gate_v3_admission_build_admission_statement_built"],
  ["gate-v3-admission-build-admission-statement-refuse-status.fungi","gateV3AdmissionBuildAdmissionStatementRefuseStatusCore",6,"gate_v3_admission_build_admission_statement_refuse_built"],
  ["gate-v3-authority-verify-terminal-vocabulary-status.fungi","gateV3AuthorityVerifyTerminalVocabularyStatusCore",6,"gate_v3_authority_verify_terminal_vocabulary_built"],
  ["gate-v3-authority-verify-deny-arm-containment-status.fungi","gateV3AuthorityVerifyDenyArmContainmentStatusCore",6,"gate_v3_authority_verify_deny_arm_containment_built"],
  ["gate-v3-authority-verify-decision-shapes-status.fungi","gateV3AuthorityVerifyDecisionShapesStatusCore",6,"gate_v3_authority_verify_decision_shapes_built"],
  ["gate-v3-budget-compose-worst-case-budgets-status.fungi","gateV3BudgetComposeWorstCaseBudgetsStatusCore",6,"gate_v3_budget_compose_worst_case_budgets_built"],
  ["gate-v3-budget-verify-budget-composition-status.fungi","gateV3BudgetVerifyBudgetCompositionStatusCore",6,"gate_v3_budget_verify_budget_composition_built"],
  ["gate-v3-condense-by-code-unit-status.fungi","gateV3CondenseByCodeUnitStatusCore",6,"gate_v3_condense_by_code_unit_built"],
].map(([file,flow,count,expected])=>Object.freeze({file,flow,args:Array(count).fill(true),expected})));
async function api(){const load=async p=>import(pathToFileURL(join(SLIDE_ROOT,"src",p)).href);return {...await load("checked-fungi-package-compiler.mjs"),...await load("checked-fungi-package-file.mjs"),...await load("checked-fungi-package-publication-loader.mjs"),...await load("safe-value-envelope.mjs"),...await load("portable-veo.mjs")};}function expectation(r){return {packageSetDigest:r.packageSetDigest,packageIdentity:r.packageIdentity,exportName:r.exportName,receiptDigest:r.receiptDigest,safeValueTypeId:r.safeValueTypeId,safeValueStateId:r.safeValueStateId,safeValueProvenanceDigest:r.safeValueProvenanceDigest};}
it("publishes and independently re-admits all 40 wave-30 source decisions through physical SLIDE/VOK",{skip:!AVAILABLE},async()=>{const slide=await api(),context=slide.portableVeoReferenceContext(),sources=CANDIDATES.map(c=>Uint8Array.from(readFileSync(join(ROOT,c.file)))),request=bytes=>({packages:[{identity:"@galerina/test",version:"1.0.0-beta.30",exports:CANDIDATES.map((c,i)=>({name:c.flow,sourceFlowName:c.flow,sourceBytes:bytes[i]})),dependencies:[],resources:[]}],context,gates:GATES}),compiled=slide.compileCheckedFungiPackageSet(request(sources));assert.equal(compiled.verdict,1,JSON.stringify(compiled));const changed=sources.map(source=>Uint8Array.from(source));changed[0][0]^=1;assert.equal(slide.compileCheckedFungiPackageSet(request(changed)).verdict,-1);const parent=await mkdtemp(join(tmpdir(),"galerina-wave-30-")),out=join(parent,"published");try{const published=await slide.publishCheckedFungiPackageBuild({packageBuildHandle:compiled.packageBuildHandle,outputDirectory:out});assert.equal(published.verdict,1,JSON.stringify(published));assert.equal(published.outputFiles.filter(n=>n.endsWith(".slide")).length,40);let last;for(const c of CANDIDATES){const prepared=await slide.prepareCheckedFungiPackagePublication({publicationDirectory:out,packageIdentity:"@galerina/test",exportName:c.flow,context,gates:GATES});assert.equal(prepared.verdict,1,c.flow);const receipt=slide.executeTypedCheckedFungiPackagePublication(prepared.packageExecutionHandle,c.args,undefined),verified=slide.verifyTypedCheckedFungiPackageReceipt(receipt,expectation(receipt));assert.equal(verified.verdict,1,c.flow);assert.equal(verified.value,c.expected,c.flow);assert.equal(verified.authorityReleased,false,c.flow);last=receipt;}assert.equal(slide.verifyTypedCheckedFungiPackageReceipt({...last,receiptDigest:"sha256:"+"0".repeat(64)},expectation(last)).verdict,-1);const path=join(out,published.outputFiles.find(n=>n.endsWith(".slide")));const bytes=await readFile(path);bytes[0]^=1;await writeFile(path,bytes);assert.equal((await slide.prepareCheckedFungiPackagePublication({publicationDirectory:out,packageIdentity:"@galerina/test",exportName:CANDIDATES[0].flow,context,gates:GATES})).verdict,-1);}finally{await rm(parent,{recursive:true,force:true});}});
