import assert from "node:assert/strict";import { existsSync, readFileSync } from "node:fs";import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";import { tmpdir } from "node:os";import { join } from "node:path";import { pathToFileURL } from "node:url";import { it } from "node:test";
const SLIDE_ROOT=process.env.GALERINA_SLIDE_REPO,AVAILABLE=typeof SLIDE_ROOT==="string"&&existsSync(join(SLIDE_ROOT,"src","checked-fungi-package-compiler.mjs")),ROOT=join(process.cwd(),"packages-ts","galerina-test","src","self-hosted","conversion-overlays"),GATES=Object.freeze({identity:1,provenance:1,target:1,effects:1,policy:1,revocation:1,validation:1,memory:1});
const CANDIDATES=Object.freeze([
  ["type-checker-check-types-status.fungi","typeCheckerCheckTypesStatusCore",4,"type_checker_check_types_built"],
  ["type-checker-levenshtein-status.fungi","typeCheckerLevenshteinStatusCore",4,"type_checker_levenshtein_built"],
  ["type-checker-parse-binding-name-status.fungi","typeCheckerParseBindingNameStatusCore",4,"type_checker_parse_binding_name_built"],
  ["type-checker-parse-param-name-status.fungi","typeCheckerParseParamNameStatusCore",4,"type_checker_parse_param_name_built"],
  ["type-checker-type-checker-status.fungi","typeCheckerTypeCheckerStatusCore",4,"type_checker_type_checker_built"],
  ["type-checker-constructor-status.fungi","typeCheckerConstructorStatusCore",4,"type_checker_constructor_built"],
  ["type-checker-check-status.fungi","typeCheckerCheckStatusCore",4,"type_checker_check_built"],
  ["type-checker-check-and-register-binding-type-status.fungi","typeCheckerCheckAndRegisterBindingTypeStatusCore",4,"type_checker_check_and_register_binding_type_built"],
  ["type-checker-check-binary-operator-types-status.fungi","typeCheckerCheckBinaryOperatorTypesStatusCore",4,"type_checker_check_binary_operator_types_built"],
  ["type-checker-check-binding-type-annotation-status.fungi","typeCheckerCheckBindingTypeAnnotationStatusCore",4,"type_checker_check_binding_type_annotation_built"],
  ["type-checker-check-check-subject-status.fungi","typeCheckerCheckCheckSubjectStatusCore",4,"type_checker_check_check_subject_built"],
  ["type-checker-check-condition-bool-status.fungi","typeCheckerCheckConditionBoolStatusCore",4,"type_checker_check_condition_bool_built"],
  ["type-checker-check-int-literal-range-status.fungi","typeCheckerCheckIntLiteralRangeStatusCore",4,"type_checker_check_int_literal_range_built"],
  ["type-checker-check-k3-unary-and-folds-status.fungi","typeCheckerCheckK3UnaryAndFoldsStatusCore",4,"type_checker_check_k3_unary_and_folds_built"],
  ["type-checker-check-match-exhaustiveness-status.fungi","typeCheckerCheckMatchExhaustivenessStatusCore",4,"type_checker_check_match_exhaustiveness_built"],
  ["type-checker-check-money-currency-tag-status.fungi","typeCheckerCheckMoneyCurrencyTagStatusCore",4,"type_checker_check_money_currency_tag_built"],
  ["type-checker-check-prefilter-subject-status.fungi","typeCheckerCheckPrefilterSubjectStatusCore",4,"type_checker_check_prefilter_subject_built"],
  ["type-checker-check-shadowed-binding-status.fungi","typeCheckerCheckShadowedBindingStatusCore",4,"type_checker_check_shadowed_binding_built"],
  ["type-checker-check-type-ref-status.fungi","typeCheckerCheckTypeRefStatusCore",4,"type_checker_check_type_ref_built"],
  ["type-checker-emit-hallmark-op-denied-status.fungi","typeCheckerEmitHallmarkOpDeniedStatusCore",4,"type_checker_emit_hallmark_op_denied_built"],
  ["type-checker-fuzzy-single-candidate-status.fungi","typeCheckerFuzzySingleCandidateStatusCore",4,"type_checker_fuzzy_single_candidate_built"],
  ["type-checker-fuzzy-type-suggestion-status.fungi","typeCheckerFuzzyTypeSuggestionStatusCore",4,"type_checker_fuzzy_type_suggestion_built"],
  ["type-checker-infer-type-status.fungi","typeCheckerInferTypeStatusCore",4,"type_checker_infer_type_built"],
  ["type-checker-is-reserved-hallmark-name-status.fungi","typeCheckerIsReservedHallmarkNameStatusCore",4,"type_checker_is_reserved_hallmark_name_built"],
  ["type-checker-lookup-binding-status.fungi","typeCheckerLookupBindingStatusCore",4,"type_checker_lookup_binding_built"],
  ["type-checker-lookup-binding-type-status.fungi","typeCheckerLookupBindingTypeStatusCore",4,"type_checker_lookup_binding_type_built"],
  ["type-checker-match-arm-payload-type-status.fungi","typeCheckerMatchArmPayloadTypeStatusCore",4,"type_checker_match_arm_payload_type_built"],
  ["type-checker-pop-type-scope-status.fungi","typeCheckerPopTypeScopeStatusCore",4,"type_checker_pop_type_scope_built"],
  ["type-checker-push-type-scope-status.fungi","typeCheckerPushTypeScopeStatusCore",4,"type_checker_push_type_scope_built"],
  ["type-checker-register-binding-status.fungi","typeCheckerRegisterBindingStatusCore",4,"type_checker_register_binding_built"],
  ["type-checker-register-binding-type-status.fungi","typeCheckerRegisterBindingTypeStatusCore",4,"type_checker_register_binding_type_built"],
  ["type-checker-walk-node-status.fungi","typeCheckerWalkNodeStatusCore",4,"type_checker_walk_node_built"],
  ["type-registry-effects-subset-status.fungi","typeRegistryEffectsSubsetStatusCore",4,"type_registry_effects_subset_built"],
  ["type-registry-effects-to-flags-status.fungi","typeRegistryEffectsToFlagsStatusCore",4,"type_registry_effects_to_flags_built"],
  ["type-registry-parse-tensor-type-status.fungi","typeRegistryParseTensorTypeStatusCore",4,"type_registry_parse_tensor_type_built"],
  ["type-registry-resolve-type-id-status.fungi","typeRegistryResolveTypeIdStatusCore",4,"type_registry_resolve_type_id_built"],
  ["type-registry-tensor-dimension-counts-compatible-status.fungi","typeRegistryTensorDimensionCountsCompatibleStatusCore",4,"type_registry_tensor_dimension_counts_compatible_built"],
  ["type-registry-tensor-element-types-compatible-status.fungi","typeRegistryTensorElementTypesCompatibleStatusCore",4,"type_registry_tensor_element_types_compatible_built"],
  ["effect-checker-format-effects-status.fungi","effectCheckerFormatEffectsStatusCore",4,"effect_checker_format_effects_built"],
  ["effect-checker-unique-status.fungi","effectCheckerUniqueStatusCore",4,"effect_checker_unique_built"],
].map(([file,flow,count,expected])=>Object.freeze({file,flow,args:Array(count).fill(true),expected})));
async function api(){const load=async p=>import(pathToFileURL(join(SLIDE_ROOT,"src",p)).href);return {...await load("checked-fungi-package-compiler.mjs"),...await load("checked-fungi-package-file.mjs"),...await load("checked-fungi-package-publication-loader.mjs"),...await load("safe-value-envelope.mjs"),...await load("portable-veo.mjs")};}function expectation(r){return {packageSetDigest:r.packageSetDigest,packageIdentity:r.packageIdentity,exportName:r.exportName,receiptDigest:r.receiptDigest,safeValueTypeId:r.safeValueTypeId,safeValueStateId:r.safeValueStateId,safeValueProvenanceDigest:r.safeValueProvenanceDigest};}
it("publishes and independently re-admits all 40 wave-27 source decisions through physical SLIDE/VOK",{skip:!AVAILABLE},async()=>{const slide=await api(),context=slide.portableVeoReferenceContext(),sources=CANDIDATES.map(c=>Uint8Array.from(readFileSync(join(ROOT,c.file)))),request=bytes=>({packages:[{identity:"@galerina/test",version:"1.0.0-beta.27",exports:CANDIDATES.map((c,i)=>({name:c.flow,sourceFlowName:c.flow,sourceBytes:bytes[i]})),dependencies:[],resources:[]}],context,gates:GATES}),compiled=slide.compileCheckedFungiPackageSet(request(sources));assert.equal(compiled.verdict,1,JSON.stringify(compiled));const changed=sources.map(source=>Uint8Array.from(source));changed[0][0]^=1;assert.equal(slide.compileCheckedFungiPackageSet(request(changed)).verdict,-1);const parent=await mkdtemp(join(tmpdir(),"galerina-wave-27-")),out=join(parent,"published");try{const published=await slide.publishCheckedFungiPackageBuild({packageBuildHandle:compiled.packageBuildHandle,outputDirectory:out});assert.equal(published.verdict,1,JSON.stringify(published));assert.equal(published.outputFiles.filter(n=>n.endsWith(".slide")).length,40);let last;for(const c of CANDIDATES){const prepared=await slide.prepareCheckedFungiPackagePublication({publicationDirectory:out,packageIdentity:"@galerina/test",exportName:c.flow,context,gates:GATES});assert.equal(prepared.verdict,1,c.flow);const receipt=slide.executeTypedCheckedFungiPackagePublication(prepared.packageExecutionHandle,c.args,undefined),verified=slide.verifyTypedCheckedFungiPackageReceipt(receipt,expectation(receipt));assert.equal(verified.verdict,1,c.flow);assert.equal(verified.value,c.expected,c.flow);assert.equal(verified.authorityReleased,false,c.flow);last=receipt;}assert.equal(slide.verifyTypedCheckedFungiPackageReceipt({...last,receiptDigest:"sha256:"+"0".repeat(64)},expectation(last)).verdict,-1);const path=join(out,published.outputFiles.find(n=>n.endsWith(".slide")));const bytes=await readFile(path);bytes[0]^=1;await writeFile(path,bytes);assert.equal((await slide.prepareCheckedFungiPackagePublication({publicationDirectory:out,packageIdentity:"@galerina/test",exportName:CANDIDATES[0].flow,context,gates:GATES})).verdict,-1);}finally{await rm(parent,{recursive:true,force:true});}});
