// roadmap-subway-generator.test.mjs — proves selected-root, preflighted
// roadmap/SVG generation and non-mutating whole-artifact drift refusal.
// Version: 1.0.0 · Task 7 generator governance.
// Related: scripts/gen-roadmap-subway.mjs; scripts/component-health.mjs.
import { test } from "node:test";
import assert from "node:assert/strict";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { createHash } from "node:crypto";

const SCRIPT = resolve("scripts/gen-roadmap-subway.mjs");
const PROVENANCE = resolve("scripts/lib/provenance.mjs");
const ROADMAP_EVIDENCE = resolve("scripts/lib/assurance-fabric/roadmap-evidence.mjs");
const GENERATED_EVIDENCE = resolve("scripts/lib/assurance-fabric/generated-evidence.mjs");
const EVIDENCE_DAG = resolve("scripts/lib/assurance-fabric/evidence-dag.mjs");
const STRICT_JSON = resolve("scripts/lib/assurance-fabric/strict-json.mjs");
const DEPENDENCIES = resolve("governance/assurance-evidence-dependencies.json");
const BEGIN =
  "<!-- SUBWAY:BEGIN (generated by scripts/gen-roadmap-subway.mjs — do not edit; run `node scripts/gen-roadmap-subway.mjs --write`) -->";
const END = "<!-- SUBWAY:END -->";

/**
 * Write one fixture file, creating its parent directories.
 *
 * @param {string} root fixture root
 * @param {string} relativePath fixture-relative path
 * @param {string} content exact content
 */
function write(root, relativePath, content) {
  const path = join(root, relativePath);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

/**
 * Install hand-derived ledgers, component-health output, and both marker-owned
 * targets in one repository root.
 */
function installRepository(root) {
  const stageNames = [
    "lexer",
    "parser",
    "type-checker",
    "effect-checker",
    "gir-emitter",
    "governance-verifier",
    "runtime",
  ];
  write(
    root,
    "docs/security/rd0528-compiler-stage-hashes-baseline.json",
    JSON.stringify({
      stages: Object.fromEntries(stageNames.map((name) => [name, { sha256: name }])),
    }),
  );
  write(
    root,
    "docs/security/rd0528-compiler-authoritative-stages.json",
    JSON.stringify({ twins: [{ file: "lexer.fungi" }] }),
  );
  write(
    root,
    "docs/security/rd0361-authoritative-twins.json",
    JSON.stringify({ twins: [{ file: "memory.fungi" }] }),
  );
  write(
    root,
    "version.json",
    JSON.stringify({ version: "0.0.1", packageCount: 2, testCount: 3 }),
  );
  const percentAudit = {
    shipReadinessPct: 25,
    ztAvg: 50,
    buildAvg: 75,
    provenance: { branch: "fixture", sha: "fixture", dirty: true },
    sections: [
      {
        key: "zero-trust-thesis",
        rows: [{ label: "Boundary", pct: 50, evidence: { live: "fixture" } }],
      },
      {
        key: "build-progress",
        rows: [{ label: "Layer", pct: 75, evidence: { asserted: "fixture" } }],
      },
      {
        key: "tracking-registry",
        rows: [{ item: "Workstream", state: "building" }],
      },
    ],
  };
  write(
    root,
    "scripts/component-health.mjs",
    `console.log(${JSON.stringify(JSON.stringify({ percentAudit }))});\n`,
  );
  for (const target of [
    "README.md",
    "docs/roadmap-2026-07-25-cycle2.md",
    "docs/roadmap-2026-07-29-galerina-beta-v1-to-slide.md",
  ]) {
    write(root, target, `before\r\n${BEGIN}\r\nstale\r\n${END}\r\nafter\r\n`);
  }
}

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

function installEvidence(root, head) {
  const dependencies = JSON.parse(readFileSync(DEPENDENCIES, "utf8"));
  write(root, "governance/assurance-evidence-dependencies.json", `${JSON.stringify(dependencies, undefined, 2)}\n`);
  for (const node of dependencies.nodes) {
    for (const artifactPath of node.artifactPaths) write(root, artifactPath, `${node.id}:${artifactPath}\n`);
    if (node.toolPath !== "scripts/component-health.mjs") {
      write(root, node.toolPath, `export const tool = ${JSON.stringify(node.expectedTool)};\n`);
    }
    const external = node.externalInputPolicy === "required"
      ? { externalInputDigest: sha256(`${node.id}:external`), externalDocumentCount: 1 }
      : {};
    write(root, node.provenancePath, `${JSON.stringify({
      tool: node.expectedTool,
      gitCommit: head,
      builtAt: "2026-08-10T00:00:00.000Z",
      node: process.version,
      ...external,
    }, undefined, 2)}\n`);
  }
  write(root, dependencies.root.toolPath, readFileSync(SCRIPT, "utf8"));
}

/**
 * Keep the copied generator harness distinct from the selected repository.
 */
function fixture() {
  const harness = mkdtempSync(join(tmpdir(), "roadmap-subway-generator-"));
  const selected = join(harness, "selected");
  write(harness, "package.json", '{"type":"module"}\n');
  write(harness, "scripts/gen-roadmap-subway.mjs", readFileSync(SCRIPT, "utf8"));
  write(harness, "scripts/lib/provenance.mjs", readFileSync(PROVENANCE, "utf8"));
  write(harness, "scripts/lib/assurance-fabric/roadmap-evidence.mjs", readFileSync(ROADMAP_EVIDENCE, "utf8"));
  write(harness, "scripts/lib/assurance-fabric/generated-evidence.mjs", readFileSync(GENERATED_EVIDENCE, "utf8"));
  write(harness, "scripts/lib/assurance-fabric/evidence-dag.mjs", readFileSync(EVIDENCE_DAG, "utf8"));
  write(harness, "scripts/lib/assurance-fabric/strict-json.mjs", readFileSync(STRICT_JSON, "utf8"));
  installRepository(harness);
  installRepository(selected);
  assert.equal(spawnSync("git", ["init"], { cwd: selected }).status, 0);
  assert.equal(spawnSync("git", ["config", "user.email", "fixture@example.invalid"], { cwd: selected }).status, 0);
  assert.equal(spawnSync("git", ["config", "user.name", "Fixture"], { cwd: selected }).status, 0);
  assert.equal(spawnSync("git", ["add", "--", "."], { cwd: selected }).status, 0);
  assert.equal(spawnSync("git", ["commit", "-m", "fixture"], { cwd: selected }).status, 0);
  const head = spawnSync("git", ["rev-parse", "HEAD"], { cwd: selected, encoding: "utf8" }).stdout.trim();
  installEvidence(selected, head);
  return { harness, selected };
}

/**
 * Run the copied real generator against the selected fixture root.
 *
 * @param {string} harness harness root
 * @param {string} selected selected repository root
 * @param {readonly string[]} args generator mode arguments
 */
function run(harness, selected, args = []) {
  return spawnSync(
    process.execPath,
    [join(harness, "scripts", "gen-roadmap-subway.mjs"), "--root", selected, ...args],
    {
      encoding: "utf8",
      env: { ...process.env, SOURCE_DATE_EPOCH: "1700000000" },
    },
  );
}

test("roadmap subway preflights and checks every selected-root output", () => {
  const { harness, selected } = fixture();
  const svg = join(selected, "build/component-health/roadmap-subway.svg");
  const provenance = join(selected, "build/component-health/subway-provenance.json");
  const readme = join(selected, "README.md");
  const roadmap = join(selected, "docs/roadmap-2026-07-25-cycle2.md");
  try {
    const missing = run(harness, selected, ["--check"]);
    assert.notEqual(missing.status, 0);
    assert.equal(existsSync(svg), false);

    const generated = run(harness, selected, ["--write"]);
    assert.equal(generated.status, 0, generated.stderr);
    assert.equal(existsSync(svg), true);
    assert.equal(existsSync(provenance), true);
    assert.match(readFileSync(readme, "utf8"), /Tracking registry \(1\)/);
    assert.match(readFileSync(readme, "utf8"), /Assurance DAG: CURRENT/);
    assert.match(readFileSync(svg, "utf8"), /Workstream/);
    assert.match(readFileSync(svg, "utf8"), /Assurance DAG: CURRENT/);
    assert.equal(run(harness, selected, ["--check"]).status, 0);

    writeFileSync(svg, "tampered\n");
    const readmeBefore = readFileSync(readme, "utf8");
    const roadmapBefore = readFileSync(roadmap, "utf8");
    const drifted = run(harness, selected, ["--check"]);
    assert.notEqual(drifted.status, 0);
    assert.equal(readFileSync(svg, "utf8"), "tampered\n");
    assert.equal(readFileSync(readme, "utf8"), readmeBefore);
    assert.equal(readFileSync(roadmap, "utf8"), roadmapBefore);

    assert.equal(run(harness, selected, ["--write"]).status, 0);
    const svgBefore = readFileSync(svg, "utf8");
    writeFileSync(roadmap, "markerless\n");
    const unsafeWrite = run(harness, selected, ["--write"]);
    assert.notEqual(unsafeWrite.status, 0);
    assert.equal(readFileSync(svg, "utf8"), svgBefore);

    installRepository(selected);
    assert.equal(run(harness, selected, ["--write"]).status, 0);
    writeFileSync(provenance, "tampered\n");
    const provenanceDrift = run(harness, selected, ["--check"]);
    assert.notEqual(provenanceDrift.status, 0);
    assert.equal(readFileSync(provenance, "utf8"), "tampered\n");
  } finally {
    rmSync(harness, { recursive: true, force: true });
  }
});

test("roadmap renders stale predecessors as unknown and refuses deny evidence", () => {
  const { harness, selected } = fixture();
  const svg = join(selected, "build/component-health/roadmap-subway.svg");
  try {
    assert.equal(run(harness, selected, ["--write"]).status, 0);
    const graphProvenance = join(selected, "build/graph/provenance.json");
    const stale = JSON.parse(readFileSync(graphProvenance, "utf8"));
    stale.gitCommit = "b".repeat(40);
    writeFileSync(graphProvenance, `${JSON.stringify(stale, undefined, 2)}\n`);
    const unknown = run(harness, selected, ["--write"]);
    assert.equal(unknown.status, 0, unknown.stderr);
    assert.match(readFileSync(svg, "utf8"), /Assurance DAG: UNKNOWN/);

    writeFileSync(join(selected, "build/kb-graph/provenance.json"), "{\"tool\":\"kb-graph-generator\"}\n");
    const before = readFileSync(svg, "utf8");
    const denied = run(harness, selected, ["--write"]);
    assert.notEqual(denied.status, 0);
    assert.equal(readFileSync(svg, "utf8"), before);
  } finally {
    rmSync(harness, { recursive: true, force: true });
  }
});
