// roadmap-subway-generator.test.mjs — proves selected-root, preflighted
// roadmap/SVG generation and non-mutating whole-artifact drift refusal.
// Version: 1.0.0 · Task 7 generator governance.
// Related: scripts/gen-roadmap-subway.mjs; scripts/component-health.mjs.
import { test } from "node:test";
import assert from "node:assert/strict";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";

const SCRIPT = resolve("scripts/gen-roadmap-subway.mjs");
const PROVENANCE = resolve("scripts/lib/provenance.mjs");
const BEGIN =
  "<!-- SUBWAY:BEGIN (generated by scripts/gen-roadmap-subway.mjs — do not edit; run `node scripts/gen-roadmap-subway.mjs --write`) -->";
const END = "<!-- SUBWAY:END -->";

/**
 * Write one fixture file, creating its parent directories.
 *
 * @param {string} root fixture root
 * @param {string} relativePath fixture-relative path
 * @param {string} content exact content
 */
function write(root, relativePath, content) {
  const path = join(root, relativePath);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

/**
 * Install hand-derived ledgers, component-health output, and both marker-owned
 * targets in one repository root.
 */
function installRepository(root) {
  const stageNames = [
    "lexer",
    "parser",
    "type-checker",
    "effect-checker",
    "gir-emitter",
    "governance-verifier",
    "runtime",
  ];
  write(
    root,
    "docs/security/rd0528-compiler-stage-hashes-baseline.json",
    JSON.stringify({
      stages: Object.fromEntries(stageNames.map((name) => [name, { sha256: name }])),
    }),
  );
  write(
    root,
    "docs/security/rd0528-compiler-authoritative-stages.json",
    JSON.stringify({ twins: [{ file: "lexer.fungi" }] }),
  );
  write(
    root,
    "docs/security/rd0361-authoritative-twins.json",
    JSON.stringify({ twins: [{ file: "memory.fungi" }] }),
  );
  write(
    root,
    "version.json",
    JSON.stringify({ version: "0.0.1", packageCount: 2, testCount: 3 }),
  );
  const percentAudit = {
    shipReadinessPct: 25,
    ztAvg: 50,
    buildAvg: 75,
    provenance: { branch: "fixture", sha: "fixture", dirty: true },
    sections: [
      {
        key: "zero-trust-thesis",
        rows: [{ label: "Boundary", pct: 50, evidence: { live: "fixture" } }],
      },
      {
        key: "build-progress",
        rows: [{ label: "Layer", pct: 75, evidence: { asserted: "fixture" } }],
      },
      {
        key: "tracking-registry",
        rows: [{ item: "Workstream", state: "building" }],
      },
    ],
  };
  write(
    root,
    "scripts/component-health.mjs",
    `console.log(${JSON.stringify(JSON.stringify({ percentAudit }))});\n`,
  );
  for (const target of [
    "README.md",
    "docs/roadmap-2026-07-25-cycle2.md",
  ]) {
    write(root, target, `before\r\n${BEGIN}\r\nstale\r\n${END}\r\nafter\r\n`);
  }
}

/**
 * Keep the copied generator harness distinct from the selected repository.
 */
function fixture() {
  const harness = mkdtempSync(join(tmpdir(), "roadmap-subway-generator-"));
  const selected = join(harness, "selected");
  write(harness, "package.json", '{"type":"module"}\n');
  write(harness, "scripts/gen-roadmap-subway.mjs", readFileSync(SCRIPT, "utf8"));
  write(harness, "scripts/lib/provenance.mjs", readFileSync(PROVENANCE, "utf8"));
  installRepository(harness);
  installRepository(selected);
  assert.equal(spawnSync("git", ["init"], { cwd: selected }).status, 0);
  assert.equal(spawnSync("git", ["add", "--", "."], { cwd: selected }).status, 0);
  return { harness, selected };
}

/**
 * Run the copied real generator against the selected fixture root.
 *
 * @param {string} harness harness root
 * @param {string} selected selected repository root
 * @param {readonly string[]} args generator mode arguments
 */
function run(harness, selected, args = []) {
  return spawnSync(
    process.execPath,
    [join(harness, "scripts", "gen-roadmap-subway.mjs"), "--root", selected, ...args],
    {
      encoding: "utf8",
      env: { ...process.env, SOURCE_DATE_EPOCH: "1700000000" },
    },
  );
}

test("roadmap subway preflights and checks every selected-root output", () => {
  const { harness, selected } = fixture();
  const svg = join(selected, "build/component-health/roadmap-subway.svg");
  const provenance = join(selected, "build/component-health/provenance.json");
  const readme = join(selected, "README.md");
  const roadmap = join(selected, "docs/roadmap-2026-07-25-cycle2.md");
  try {
    const missing = run(harness, selected, ["--check"]);
    assert.notEqual(missing.status, 0);
    assert.equal(existsSync(svg), false);

    const generated = run(harness, selected, ["--write"]);
    assert.equal(generated.status, 0, generated.stderr);
    assert.equal(existsSync(svg), true);
    assert.equal(existsSync(provenance), true);
    assert.match(readFileSync(readme, "utf8"), /Tracking registry \(1\)/);
    assert.match(readFileSync(svg, "utf8"), /Workstream/);
    assert.equal(run(harness, selected, ["--check"]).status, 0);

    writeFileSync(svg, "tampered\n");
    const readmeBefore = readFileSync(readme, "utf8");
    const roadmapBefore = readFileSync(roadmap, "utf8");
    const drifted = run(harness, selected, ["--check"]);
    assert.notEqual(drifted.status, 0);
    assert.equal(readFileSync(svg, "utf8"), "tampered\n");
    assert.equal(readFileSync(readme, "utf8"), readmeBefore);
    assert.equal(readFileSync(roadmap, "utf8"), roadmapBefore);

    assert.equal(run(harness, selected, ["--write"]).status, 0);
    const svgBefore = readFileSync(svg, "utf8");
    writeFileSync(roadmap, "markerless\n");
    const unsafeWrite = run(harness, selected, ["--write"]);
    assert.notEqual(unsafeWrite.status, 0);
    assert.equal(readFileSync(svg, "utf8"), svgBefore);

    installRepository(selected);
    assert.equal(run(harness, selected, ["--write"]).status, 0);
    writeFileSync(provenance, "tampered\n");
    const provenanceDrift = run(harness, selected, ["--check"]);
    assert.notEqual(provenanceDrift.status, 0);
    assert.equal(readFileSync(provenance, "utf8"), "tampered\n");
  } finally {
    rmSync(harness, { recursive: true, force: true });
  }
});
