// status-blocks-generator.test.mjs — proves root-isolated status generation,
// exact target coverage, provenance, and non-mutating drift refusal.
// Version: 1.0.0 · Task 7 generator governance.
// Related: scripts/gen-status-blocks.mjs; scripts/component-health.mjs.
import { test } from "node:test";
import assert from "node:assert/strict";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";

const SCRIPT = resolve("scripts/gen-status-blocks.mjs");
const BEGIN = "<!-- STATUS:BEGIN (generated by scripts/gen-status-blocks.mjs — do not edit; run `node scripts/gen-status-blocks.mjs --write`) -->";
const END = "<!-- STATUS:END -->";

/**
 * Write one fixture file, creating its parent directories.
 *
 * @param {string} root fixture root
 * @param {string} relativePath fixture-relative path
 * @param {string} content exact content
 */
function write(root, relativePath, content) {
  const path = join(root, relativePath);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

/**
 * Create a minimal component-health source and both required target docs.
 */
function fixture() {
  const root = mkdtempSync(join(tmpdir(), "status-blocks-generator-"));
  const percentAudit = {
    shipReadinessPct: 25,
    ztAvg: 50,
    buildAvg: 75,
    trackingRegistryCount: 2,
    sections: [
      {
        key: "zero-trust-thesis",
        rows: [{ label: "Boundary", pct: 50 }],
      },
      {
        key: "build-progress",
        rows: [{ label: "Layer", pct: 75 }],
      },
      {
        key: "tracking-registry",
        rows: [
          { label: "Done", state: "shipped" },
          { label: "Work", state: 40 },
        ],
      },
    ],
  };
  write(
    root,
    "scripts/component-health.mjs",
    `console.log(${JSON.stringify(JSON.stringify({ percentAudit }))});\n`,
  );
  for (const target of [
    "docs/roadmap-2026-07-15.md",
    "docs/roadmap-2026-07-23.md",
  ]) {
    write(root, target, `before\n${BEGIN}\nstale\n${END}\nafter\n`);
  }
  return root;
}

/**
 * Run the real status generator against the fixture.
 *
 * @param {string} root fixture root
 * @param {readonly string[]} args generator arguments
 */
function run(root, args) {
  return spawnSync(
    process.execPath,
    [SCRIPT, "--root", root, ...args],
    {
      encoding: "utf8",
      env: { ...process.env, SOURCE_DATE_EPOCH: "1700000000" },
    },
  );
}

test("status-block --check refuses missing and drifted outputs without writing", () => {
  const root = fixture();
  const artifact = join(root, "build", "status", "STATUS.md");
  const firstTarget = join(root, "docs", "roadmap-2026-07-15.md");
  const secondTarget = join(root, "docs", "roadmap-2026-07-23.md");
  try {
    const missing = run(root, ["--check"]);
    assert.notEqual(missing.status, 0);
    assert.equal(existsSync(artifact), false);

    const generated = run(root, ["--write"]);
    assert.equal(generated.status, 0, generated.stderr);
    assert.equal(existsSync(join(root, "build", "status", "provenance.json")), true);
    assert.equal(run(root, ["--check"]).status, 0);

    writeFileSync(artifact, "tampered\n");
    const targetBefore = readFileSync(firstTarget, "utf8");
    rmSync(secondTarget);
    const drifted = run(root, ["--check"]);
    assert.notEqual(drifted.status, 0);
    assert.equal(readFileSync(artifact, "utf8"), "tampered\n");
    assert.equal(readFileSync(firstTarget, "utf8"), targetBefore);
    assert.equal(existsSync(secondTarget), false);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
