#!/usr/bin/env node
/**
 * docs-index.mjs — generate an INDEX.md for every documentation subtree.
 *
 * WHY THIS EXISTS
 * An audit on 2026-08-13 measured the docs link graph: 1543 of 1898 documents (81%) were
 * linked from no other document, and the whole graph resolved to 462 distinct targets. A
 * reader — human or agent — that starts at an index and follows links reaches under a fifth
 * of what is written here. The documents were not missing; they were unreachable.
 *
 * The fix is additive: an index per subtree, linking every document in it, and a root index
 * linking the subtrees. Nothing moves, nothing is rewritten.
 *
 * GENERATED, NOT WRITTEN. A hand-maintained index drifts the moment a file is added, and a
 * stale index answers confidently and wrongly. Re-run this after adding documents.
 *
 *   --selftest    fixtures with known answers
 *   --dry-run     report what would change
 *   --apply       write the indexes
 */

import { readdirSync, readFileSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { join, resolve, dirname, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DOCS = join(ROOT, 'docs');
const GENERATED = 'INDEX.md';
const SKIP_DIRS = new Set(['.myco', 'node_modules', '.git', 'generated']);

const toPosix = (p) => p.split(sep).join('/');

/**
 * First heading, or the first non-empty prose line, as the document's description.
 * Front-matter, headings and list markers are stripped so the line reads as a summary.
 */
export function describe(text, fallback) {
  const body = text.replace(/^---\n[\s\S]*?\n---\n/, '');
  const h1 = /^#\s+(.+)$/m.exec(body);
  if (h1) return h1[1].replace(/[`*_]/g, '').trim();
  for (const line of body.split('\n')) {
    const t = line.trim();
    if (!t || t.startsWith('#') || t.startsWith('|') || t.startsWith('---')) continue;
    return t.replace(/^[-*>]\s*/, '').replace(/[`*_]/g, '').slice(0, 120).trim();
  }
  return fallback;
}

/** Title-case a directory slug for a heading. */
export function titleOf(name) {
  return name.replace(/[-_]/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

function listDir(dir) {
  const files = [], dirs = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (SKIP_DIRS.has(e.name)) continue;
    if (e.isDirectory()) dirs.push(e.name);
    else if (/\.md$/i.test(e.name) && e.name !== GENERATED) files.push(e.name);
  }
  return { files: files.sort(), dirs: dirs.sort() };
}

function countMd(dir) {
  let n = 0;
  const stack = [dir];
  while (stack.length) {
    const d = stack.pop();
    let es;
    try { es = readdirSync(d, { withFileTypes: true }); } catch { continue; }
    for (const e of es) {
      if (SKIP_DIRS.has(e.name)) continue;
      if (e.isDirectory()) stack.push(join(d, e.name));
      else if (/\.md$/i.test(e.name) && e.name !== GENERATED) n++;
    }
  }
  return n;
}

/**
 * Will this directory receive an INDEX.md? This predicate MUST stay identical to the write
 * loop's condition — if they disagree, a parent links an index that was never written.
 * That disagreement produced exactly five dead links on the first run.
 */
export function willIndex(dir) {
  try {
    const { files, dirs } = listDir(dir);
    return files.length > 0 || dirs.length > 0;
  } catch { return false; }
}

function buildIndex(dir) {
  const { files, dirs } = listDir(dir);
  const rel = toPosix(relative(DOCS, dir)) || '.';
  const name = rel === '.' ? 'docs' : rel;
  const depth = rel === '.' ? 0 : rel.split('/').length;

  const L = [`# ${rel === '.' ? 'Galerina documentation' : titleOf(dir.split(sep).pop())} — index`, ''];
  L.push(`\`docs/${rel === '.' ? '' : rel + '/'}\` — **${files.length}** document${files.length === 1 ? '' : 's'} here` +
    (dirs.length ? `, **${dirs.length}** subdirector${dirs.length === 1 ? 'y' : 'ies'}.` : '.'));
  L.push('');
  L.push('*Generated by `scripts/docs-index.mjs`. Do not hand-edit — re-run after adding documents.*');
  L.push('');

  if (dirs.length) {
    L.push('---', '', '## Sections', '', '| Section | Documents |', '|---|---|');
    for (const d of dirs) {
      const n = countMd(join(dir, d));
      // A directory only receives an INDEX.md if it has something to index. Linking one
      // into a directory that holds only examples or fixtures is a dead link, so those
      // rows point at the directory itself and say what is in it.
      const target = willIndex(join(dir, d)) ? `${d}/${GENERATED}` : `${d}/`;
      L.push(`| [\`${d}/\`](${target}) | ${n === 0 ? '— (no documents; browse the directory)' : n} |`);
    }
    L.push('');
  }

  if (files.length) {
    L.push('---', '', '## Documents', '', '| Document | Description |', '|---|---|');
    for (const f of files) {
      let desc = f.replace(/\.md$/i, '').replace(/[-_]/g, ' ');
      try { desc = describe(readFileSync(join(dir, f), 'utf8'), desc); } catch { /* keep fallback */ }
      L.push(`| [\`${f}\`](${f}) | ${desc.replace(/\|/g, '\\|')} |`);
    }
    L.push('');
  }

  L.push('---', '');
  if (depth > 0) {
    L.push(`[← \`docs/\` index](${'../'.repeat(depth)}${GENERATED})`);
  } else {
    L.push('This index is the entry point for the documentation tree. For the repository itself, see');
    L.push('[`../README.md`](../README.md) and [`../AGENTS.md`](../AGENTS.md).');
  }
  L.push('');
  return L.join('\n');
}

function allDirs(dir, out = []) {
  out.push(dir);
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.isDirectory() && !SKIP_DIRS.has(e.name)) allDirs(join(dir, e.name), out);
  }
  return out;
}

function selftest() {
  let pass = 0, fail = 0;
  const eq = (l, g, w) => { if (g === w) pass++; else { fail++; console.log(`  FAIL ${l}\n    got  ${JSON.stringify(g)}\n    want ${JSON.stringify(w)}`); } };

  eq('h1 becomes the description', describe('# Governance architecture\n\ntext', 'fb'), 'Governance architecture');
  eq('front matter is skipped', describe('---\ntitle: x\n---\n# Real Title\n', 'fb'), 'Real Title');
  eq('backticks stripped from heading', describe('# The `vAnd` operator', 'fb'), 'The vAnd operator');
  eq('falls back to first prose line', describe('Some opening sentence here.\n', 'fb'), 'Some opening sentence here.');
  eq('table rows are not a description', describe('| a | b |\n|---|---|\nreal line\n', 'fb'), 'real line');
  eq('empty document uses the fallback', describe('', 'fb'), 'fb');
  eq('list marker stripped', describe('- a bullet opening\n', 'fb'), 'a bullet opening');
  eq('title case', titleOf('research-prompts'), 'Research Prompts');
  eq('title case underscore', titleOf('platform_handover'), 'Platform Handover');

  // CONTROL: describe() must produce DIFFERENT answers for different documents, otherwise
  // every index row would carry the same text and the index would be decoration.
  eq('control: two documents get two descriptions',
    describe('# Alpha', 'fb') === describe('# Beta', 'fb'), false);

  // willIndex() decides BOTH whether a file is written and whether a parent links to it.
  // The two used to disagree, which put five dead links into the first generated tree.
  eq('willIndex: absent directory', willIndex(join(DOCS, '__no_such_dir__')), false);
  eq('willIndex: docs root itself', willIndex(DOCS), true);
  {
    // A directory holding only non-markdown content gets no index, so no parent may link one.
    const probe = join(DOCS, 'examples');
    if (existsSync(probe)) {
      const kids = readdirSync(probe, { withFileTypes: true }).filter((e) => e.isDirectory());
      const noIndex = kids.filter((e) => !willIndex(join(probe, e.name)));
      eq('willIndex agrees with what is on disk',
        noIndex.every((e) => !existsSync(join(probe, e.name, GENERATED))), true);
    } else pass++;
  }

  console.log(`docs-index self-test: ${fail === 0 ? `OK (${pass} fixtures)` : fail + ' FAILED'}`);
  return fail === 0;
}

const mode = process.argv[2];
if (mode === '--selftest') process.exit(selftest() ? 0 : 1);
if (!selftest()) { console.error('KATs failed — refusing to write indexes from an unproven generator.'); process.exit(1); }
if (!existsSync(DOCS)) { console.error(`no docs/ at ${DOCS}`); process.exit(2); }

const dry = mode === '--dry-run';
let written = 0, linked = 0;
for (const d of allDirs(DOCS)) {
  if (!willIndex(d)) continue;   // same predicate the Sections rows use — see willIndex()
  const { files } = listDir(d);
  const text = buildIndex(d);
  linked += files.length;
  if (!dry) writeFileSync(join(d, GENERATED), text);
  written++;
}
console.log(`${dry ? '[dry-run] would write' : 'wrote'} ${written} INDEX.md file(s), linking ${linked} documents`);
